
import { ItemType, ItemQuality, EquipmentQuality, Element, CultivationStage } from "../../../types/index.ts";
import type { TechniqueItem } from '../../../types/index.ts';

export const NHAP_MON_CONG_PHAP: { [id: string]: TechniqueItem } = {
    // ----------------------------------------------------
    // Nhóm Cơ Bản & Phổ Thông (10)
    // ----------------------------------------------------
    'luyen_khi_quyet': { id: 'luyen_khi_quyet', he: 'Chung', name: 'Luyện Khí Quyết', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.HA_PHAM, description: 'Công pháp đại trà nhất, dễ tìm thấy nhất.', effects: { cultivationSpeedModifier: 1.05 }, requirements: {}, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'nap_linh_phap': { id: 'nap_linh_phap', he: 'Chung', name: 'Nạp Linh Pháp', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Chuyên về tốc độ hấp thụ linh khí.', effects: { cultivationSpeedModifier: 1.08 }, requirements: {}, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'dan_khi_nhap_the': { id: 'dan_khi_nhap_the', he: 'Chung', name: 'Dẫn Khí Nhập Thể', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.HA_PHAM, description: 'Tập trung vào việc dẫn dắt linh khí vào cơ thể một cách ôn hoà.', effects: { cultivationSpeedModifier: 1.05 }, requirements: {}, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'tho_nap_tam_kinh': { id: 'tho_nap_tam_kinh', he: 'Chung', name: 'Thổ Nạp Tâm Kinh', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Dùng hô hấp để điều động linh khí.', effects: { cultivationSpeedModifier: 1.08, manaRecoveryRate: 1.02 }, requirements: {}, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'tu_linh_quyet': { id: 'tu_linh_quyet', he: 'Chung', name: 'Tụ Linh Quyết', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Tạo một vòng xoáy nhỏ để thu hút linh khí xung quanh.', effects: { cultivationSpeedModifier: 1.09 }, requirements: {}, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'tieu_chu_thien_hanh_cong_phap': { id: 'tieu_chu_thien_hanh_cong_phap', he: 'Chung', name: 'Tiểu Chu Thiên Hành Công Pháp', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Dạy cách vận hành chân khí theo vòng tiểu chu thiên, giúp căn cơ vững chắc.', effects: { cultivationSpeedModifier: 1.08, maxMana: 30 }, requirements: {}, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'truong_xuan_cong': { id: 'truong_xuan_cong', he: 'Dưỡng Sinh', name: 'Trường Xuân Công', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Ôn hoà, dưỡng sinh, giúp kéo dài tuổi thọ phàm nhân một chút.', effects: { cultivationSpeedModifier: 1.06, maxHealth: 75 }, requirements: {}, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'thanh_tam_quyet': { id: 'thanh_tam_quyet', he: 'Tâm', name: 'Thanh Tâm Quyết', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Giúp tâm trí thanh tịnh, tránh tẩu hoả nhập ma khi mới tu luyện.', effects: { daoTam: 8 }, requirements: {}, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'vong_nguyet_thuat': { id: 'vong_nguyet_thuat', he: 'Âm', name: 'Vọng Nguyệt Thuật', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, description: 'Hấp thu thái âm chi lực vào ban đêm, giúp linh lực thêm tinh thuần.', effects: { cultivationSpeedModifier: 1.12, magicalDefense: 30 }, requirements: {}, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'thai_duong_chan_kinh_1': { id: 'thai_duong_chan_kinh_1', he: 'Dương', name: 'Thái Dương Chân Kinh (Quyển 1)', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, description: 'Hấp thu thái dương chi khí vào buổi sáng, khí huyết cường thịnh.', effects: { cultivationSpeedModifier: 1.12, physicalDefense: 30 }, requirements: {}, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },

    // ----------------------------------------------------
    // Nhóm Ngũ Hành (15)
    // ----------------------------------------------------
    'canh_kim_quyet': { id: 'canh_kim_quyet', he: 'Kim', name: 'Canh Kim Quyết', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Linh khí sắc bén, có khuynh hướng tấn công.', effects: { cultivationSpeedModifier: 1.08, physicalAttack: 25, [Element.METAL]: 10 }, requirements: { elements: [Element.METAL] }, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'bach_de_luyen_khi_phap': { id: 'bach_de_luyen_khi_phap', he: 'Kim', name: 'Bạch Đế Luyện Khí Pháp', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Kim hệ công pháp, chú trọng sự cứng rắn.', effects: { cultivationSpeedModifier: 1.08, physicalDefense: 25, [Element.METAL]: 10 }, requirements: { elements: [Element.METAL] }, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'thanh_moc_truong_sinh_quyet': { id: 'thanh_moc_truong_sinh_quyet', he: 'Mộc', name: 'Thanh Mộc Trường Sinh Quyết', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Dưỡng thương, hồi phục tốt.', effects: { cultivationSpeedModifier: 1.08, maxHealth: 100, [Element.WOOD]: 10 }, requirements: { elements: [Element.WOOD] }, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'at_moc_duong_than_cong': { id: 'at_moc_duong_than_cong', he: 'Mộc', name: 'Ất Mộc Dưỡng Thân Công', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Mộc hệ công pháp, ôn hoà, bền bỉ.', effects: { cultivationSpeedModifier: 1.09, [Element.WOOD]: 10 }, requirements: { elements: [Element.WOOD] }, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'huyen_thuy_chan_cong': { id: 'huyen_thuy_chan_cong', he: 'Thuỷ', name: 'Huyền Thủy Chân Công', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Chân khí mềm mại, biến hoá khôn lường.', effects: { cultivationSpeedModifier: 1.08, maxMana: 70, [Element.WATER]: 10 }, requirements: { elements: [Element.WATER] }, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'quy_thuy_nhap_mon_quyet': { id: 'quy_thuy_nhap_mon_quyet', he: 'Thuỷ', name: 'Quý Thủy Nhập Môn Quyết', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Thủy hệ cơ bản, dễ tu luyện.', effects: { cultivationSpeedModifier: 1.09, [Element.WATER]: 10 }, requirements: { elements: [Element.WATER] }, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'ly_hoa_tam_kinh': { id: 'ly_hoa_tam_kinh', he: 'Hoả', name: 'Ly Hỏa Tâm Kinh', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Chân khí nóng bỏng, bộc phát mạnh.', effects: { cultivationSpeedModifier: 1.08, magicalAttack: 25, [Element.FIRE]: 10 }, requirements: { elements: [Element.FIRE] }, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'xich_duong_cong': { id: 'xich_duong_cong', he: 'Hoả', name: 'Xích Dương Công', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Hỏa hệ công pháp, tính dương cương mãnh liệt.', effects: { cultivationSpeedModifier: 1.09, [Element.FIRE]: 10 }, requirements: { elements: [Element.FIRE] }, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'mau_tho_hau_duc_cong': { id: 'mau_tho_hau_duc_cong', he: 'Thổ', name: 'Mậu Thổ Hậu Đức Công', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Chân khí trầm ổn, vững chắc, phòng ngự tốt.', effects: { cultivationSpeedModifier: 1.08, physicalDefense: 15, magicalDefense: 15, [Element.EARTH]: 10 }, requirements: { elements: [Element.EARTH] }, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'hoang_thach_luyen_the_quyet': { id: 'hoang_thach_luyen_the_quyet', he: 'Thổ, Thể', name: 'Hoàng Thạch Luyện Thể Quyết', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Thổ hệ công pháp, vừa luyện khí vừa rèn luyện thân thể.', effects: { cultivationSpeedModifier: 1.06, maxHealth: 50, physicalDefense: 10, [Element.EARTH]: 10 }, requirements: { elements: [Element.EARTH] }, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'kim_sinh_thuy_phap': { id: 'kim_sinh_thuy_phap', he: 'Kim, Thuỷ', name: 'Kim Sinh Thủy Pháp', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, description: 'Dành cho người có linh căn Kim, Thủy.', effects: { cultivationSpeedModifier: 1.13, physicalAttack: 10, maxMana: 40 }, requirements: { elements: [Element.METAL, Element.WATER] }, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'thuy_duong_moc_cong': { id: 'thuy_duong_moc_cong', he: 'Thuỷ, Mộc', name: 'Thủy Dưỡng Mộc Công', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, description: 'Dành cho người có linh căn Thủy, Mộc.', effects: { cultivationSpeedModifier: 1.13, maxMana: 40, maxHealth: 60 }, requirements: { elements: [Element.WATER, Element.WOOD] }, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'moc_sinh_hoa_quyet': { id: 'moc_sinh_hoa_quyet', he: 'Mộc, Hoả', name: 'Mộc Sinh Hỏa Quyết', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, description: 'Dành cho người có linh căn Mộc, Hỏa.', effects: { cultivationSpeedModifier: 1.13, maxHealth: 60, magicalAttack: 15 }, requirements: { elements: [Element.WOOD, Element.FIRE] }, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'hoa_luyen_tho_than': { id: 'hoa_luyen_tho_than', he: 'Hoả, Thổ', name: 'Hỏa Luyện Thổ Thân', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, description: 'Dành cho người có linh căn Hỏa, Thổ.', effects: { cultivationSpeedModifier: 1.13, magicalAttack: 15, physicalDefense: 20 }, requirements: { elements: [Element.FIRE, Element.EARTH] }, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'tho_duong_kim_kinh': { id: 'tho_duong_kim_kinh', he: 'Thổ, Kim', name: 'Thổ Dưỡng Kim Kinh', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, description: 'Dành cho người có linh căn Thổ, Kim.', effects: { cultivationSpeedModifier: 1.13, physicalDefense: 20, physicalAttack: 15 }, requirements: { elements: [Element.EARTH, Element.METAL] }, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },

    // ----------------------------------------------------
    // Nhóm Luyện Thể & Trúc Cơ (10)
    // ----------------------------------------------------
    'manh_ho_luyen_cot_cong': { id: 'manh_ho_luyen_cot_cong', he: 'Thể', name: 'Mãnh Hổ Luyện Cốt Công', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Mô phỏng loài hổ, rèn luyện gân cốt.', effects: { cultivationSpeedModifier: 1.0, physicalAttack: 30 }, requirements: {}, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'thiet_bi_cong': { id: 'thiet_bi_cong', he: 'Thể', name: 'Thiết Bì Công', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Tăng cường sức phòng ngự của da thịt.', effects: { physicalDefense: 40 }, requirements: {}, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'kinh_nguu_luyen_luc_quyet': { id: 'kinh_nguu_luyen_luc_quyet', he: 'Thể', name: 'Kình Ngưu Luyện Lực Quyết', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Tăng cường sức mạnh cơ bắp.', effects: { maxHealth: 80, physicalAttack: 15 }, requirements: {}, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'ban_thach_cong': { id: 'ban_thach_cong', he: 'Thể', name: 'Bàn Thạch Công', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Giúp thân thể vững chãi như đá tảng.', effects: { maxHealth: 50, physicalDefense: 25 }, requirements: {}, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'luu_ly_kim_than_so_giai': { id: 'luu_ly_kim_than_so_giai', he: 'Thể', name: 'Lưu Ly Kim Thân (Sơ Giải)', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, description: 'Bước đầu luyện thân thể thành bảo khí.', effects: { healthModifier: 1.05, physicalDefense: 20, magicalDefense: 20 }, requirements: {}, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'hoa_van_doan_the_phap': { id: 'hoa_van_doan_the_phap', he: 'Hoả, Thể', name: 'Hỏa Vân Đoán Thể Pháp', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, description: 'Dùng hỏa linh khí để rèn luyện cơ thể.', effects: { cultivationSpeedModifier: 1.05, maxHealth: 60, magicalDefense: 25 }, requirements: { elements: [Element.FIRE] }, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'han_bang_luyen_the_thuat': { id: 'han_bang_luyen_the_thuat', he: 'Băng, Thể', name: 'Hàn Băng Luyện Thể Thuật', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, description: 'Dùng thủy/băng linh khí để tôi luyện ý chí và thân xác.', effects: { cultivationSpeedModifier: 1.05, maxMana: 50, magicalDefense: 25 }, requirements: { elements: [Element.WATER, Element.ICE] }, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'thach_phu_cong': { id: 'thach_phu_cong', he: 'Thể', name: 'Thạch Phu Công', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Khiến da trở nên cứng như đá.', effects: { physicalDefense: 45 }, requirements: {}, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'cuong_phong_luyen_the': { id: 'cuong_phong_luyen_the', he: 'Phong, Thể', name: 'Cương Phong Luyện Thể', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, description: 'Dùng phong linh khí để rèn luyện.', effects: { cultivationSpeedModifier: 1.05, speed: 15 }, requirements: { elements: [Element.WIND] }, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'bach_thu_luyen_hinh_quyet': { id: 'bach_thu_luyen_hinh_quyet', he: 'Thể', name: 'Bách Thú Luyện Hình Quyết', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, description: 'Mô phỏng các loài yêu thú để tu luyện.', effects: { physicalAttack: 20, speed: 8 }, requirements: {}, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },

    // ----------------------------------------------------
    // Nhóm Đặc Thù (15)
    // ----------------------------------------------------
    'quy_tuc_cong': { id: 'quy_tuc_cong', he: 'Dưỡng Sinh', name: 'Quy Tức Công', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Mô phỏng hơi thở của rùa, chân khí kéo dài, sinh mệnh lực mạnh.', effects: { maxHealth: 120 }, requirements: {}, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'linh_hau_tho_nap_phap': { id: 'linh_hau_tho_nap_phap', he: 'Thể', name: 'Linh Hầu Thổ Nạp Pháp', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Mô phỏng linh hầu, thân pháp nhanh nhẹn hơn.', effects: { cultivationSpeedModifier: 1.04, speed: 10 }, requirements: {}, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'hac_tung_dan_khi_quyet': { id: 'hac_tung_dan_khi_quyet', he: 'Tâm', name: 'Hạc Tùng Dẫn Khí Quyết', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Mô phỏng hạc tiên, khí chất thoát tục.', effects: { cultivationSpeedModifier: 1.06 }, requirements: { comprehension: 50 }, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'tinh_than_quan_the_thuat': { id: 'tinh_than_quan_the_thuat', he: 'Tinh Thần', name: 'Tinh Thần Quán Thể Thuật', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, description: 'Hấp thu tinh hoa của các vì sao.', effects: { cultivationSpeedModifier: 1.12, maxMana: 40, magicalAttack: 20 }, requirements: {}, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'bang_tam_quyet': { id: 'bang_tam_quyet', he: 'Băng, Tâm', name: 'Băng Tâm Quyết', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, description: 'Giữ nội tâm tĩnh lặng như băng, thích hợp tu luyện nơi giá lạnh.', effects: { daoTam: 12 }, requirements: { elements: [Element.ICE] }, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'loi_dan_so_giai': { id: 'loi_dan_so_giai', he: 'Lôi', name: 'Lôi Dẫn Sơ Giải', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, description: 'Bước đầu cảm ứng lôi linh khí, vô cùng nguy hiểm.', effects: { cultivationSpeedModifier: 1.12, magicalAttack: 40 }, requirements: { elements: [Element.LIGHTNING], comprehension: 60 }, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'am_anh_tho_nap_phap': { id: 'am_anh_tho_nap_phap', he: 'Ám', name: 'Ám Ảnh Thổ Nạp Pháp', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Thích hợp tu luyện trong bóng tối, che giấu khí tức tốt.', effects: { cultivationSpeedModifier: 1.07 }, requirements: {}, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'phong_hanh_quyet': { id: 'phong_hanh_quyet', he: 'Phong', name: 'Phong Hành Quyết', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Tăng tốc độ hấp thu phong linh khí, giúp thân pháp nhanh hơn.', effects: { cultivationSpeedModifier: 1.08, speed: 15 }, requirements: { elements: [Element.WIND] }, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'cuu_diep_bo_de_cong': { id: 'cuu_diep_bo_de_cong', he: 'Tâm', name: 'Cửu Diệp Bồ Đề Công', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, description: 'Mượn ý niệm thảo mộc để tĩnh tâm.', effects: { cultivationSpeedModifier: 1.05, daoTam: 10 }, requirements: { comprehension: 55 }, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'van_doc_luyen_khi_kinh_tan': { id: 'van_doc_luyen_khi_kinh_tan', he: 'Độc', name: 'Vạn Độc Luyện Khí Kinh (Tàn Thiên)', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, description: 'Hấp thu độc khí để tu luyện, cực kỳ nguy hiểm.', effects: { cultivationSpeedModifier: 1.15, magicalAttack: 30 }, requirements: { daoTam: 40 }, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'huyet_sat_cong_nhap_mon': { id: 'huyet_sat_cong_nhap_mon', he: 'Huyết', name: 'Huyết Sát Công (Nhập Môn)', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, description: 'Hấp thu huyết khí, ma đạo công pháp.', effects: { cultivationSpeedModifier: 1.14, physicalAttack: 30 }, requirements: { daoTam: 35 }, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'tu_khi_dong_lai_quyet': { id: 'tu_khi_dong_lai_quyet', he: 'Chung', name: 'Tử Khí Đông Lai Quyết', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, description: 'Hấp thu một luồng tử khí đầu tiên khi mặt trời mọc.', effects: { cultivationSpeedModifier: 1.13 }, requirements: { comprehension: 65 }, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'troc_khi_doan_the_phap': { id: 'troc_khi_doan_the_phap', he: 'Thể', name: 'Trọc Khí Đoán Thể Pháp', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Luyện hoá trọc khí dưới lòng đất, tiến triển chậm nhưng nền tảng vững.', effects: { physicalDefense: 25, magicalDefense: 25 }, requirements: {}, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'dia_sat_luyen_khi_thuat': { id: 'dia_sat_luyen_khi_thuat', he: 'Sát', name: 'Địa Sát Luyện Khí Thuật', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Hấp thu địa sát chi khí.', effects: { cultivationSpeedModifier: 1.08, physicalAttack: 15 }, requirements: {}, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
    'thien_cuong_chinh_phap': { id: 'thien_cuong_chinh_phap', he: 'Chung', name: 'Thiên Cương Chính Pháp', type: ItemType.CULTIVATION_METHOD, quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, description: 'Hấp thu thiên cương chi khí.', effects: { cultivationSpeedModifier: 1.08, physicalDefense: 15 }, requirements: {}, maxCultivationStage: CultivationStage.FOUNDATION_ESTABLISHMENT },
};