
import { ItemQuality } from '../../../../types/index.ts';
import { Recipe } from '../../../../types/index.ts';

export const TU_GIAI_NON_RECIPES: Record<string, Recipe> = {
    'craft_tu_giai_non_tu_la_dien': { id: 'craft_tu_giai_non_tu_la_dien', name: 'Chế tạo Tu La Diện', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'yeu_cot_tu_la_vuong_tu_giai': 1, 'lac_duong_huyet_tinh': 5 }, outputs: [{ itemId: 'tu_giai_non_tu_la_dien', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_non_tu_la_dien' },
    'craft_tu_giai_non_bat_dong_khoi': { id: 'craft_tu_giai_non_bat_dong_khoi', name: 'Chế tạo Bất Động Khôi', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'huyen_cuong_thach': 15, 'hau_tho_huyen_tinh': 5 }, outputs: [{ itemId: 'tu_giai_non_bat_dong_khoi', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_non_bat_dong_khoi' },
    'craft_tu_giai_non_thai_thanh_kinh': { id: 'craft_tu_giai_non_thai_thanh_kinh', name: 'Chế tạo Thái Thanh Kính', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'thai_at_bach_kim': 10, 'ngan_quang_huyen_thiet': 5 }, outputs: [{ itemId: 'tu_giai_non_thai_thanh_kinh', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_non_thai_thanh_kinh' },
    'craft_tu_giai_non_thien_tu_mien': { id: 'craft_tu_giai_non_thien_tu_mien', name: 'Chế tạo Thiên Tử Miện', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'tu_kim_khoang': 15, 'thai_at_bach_kim': 2 }, outputs: [{ itemId: 'tu_giai_non_thien_tu_mien', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_non_thien_tu_mien' },
    'craft_tu_giai_non_ma_long_khoi': { id: 'craft_tu_giai_non_ma_long_khoi', name: 'Chế tạo Ma Long Khôi', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'yeu_cot_thuong_co_ma_long_tu_giai': 1, 'hac_dieu_bao_ngoc': 5 }, outputs: [{ itemId: 'tu_giai_non_ma_long_khoi', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_non_ma_long_khoi' },
    'craft_tu_giai_non_tu_linh_mien': { id: 'craft_tu_giai_non_tu_linh_mien', name: 'Chế tạo Tụ Linh Miện', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'ngu_hanh_linh_ngoc': 8, 'tinh_van_tinh_thiet': 4 }, outputs: [{ itemId: 'tu_giai_non_tu_linh_mien', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_non_tu_linh_mien' },
    'craft_tu_giai_non_thu_vuong_khoi': { id: 'craft_tu_giai_non_thu_vuong_khoi', name: 'Chế tạo Thú Vương Khôi', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'yeu_cot_thanh_ho_tu_giai': 1, 'yeu_bi_tu_giai': 10 }, outputs: [{ itemId: 'tu_giai_non_thu_vuong_khoi', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_non_thu_vuong_khoi' },
    'craft_tu_giai_non_hoa_nguyen_kinh': { id: 'craft_tu_giai_non_hoa_nguyen_kinh', name: 'Chế tạo Hóa Nguyên Kính', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'yeu_cot_thon_phe_thu_tu_giai': 1, 'ngu_hanh_linh_ngoc': 5 }, outputs: [{ itemId: 'tu_giai_non_hoa_nguyen_kinh', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_non_hoa_nguyen_kinh' },
    'craft_tu_giai_non_tang_hon_dien': { id: 'craft_tu_giai_non_tang_hon_dien', name: 'Chế tạo Tàng Hồn Diện', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'hac_dieu_bao_ngoc': 12, 'minh_uyen_han_thiet': 4 }, outputs: [{ itemId: 'tu_giai_non_tang_hon_dien', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_non_tang_hon_dien' },
    'craft_tu_giai_non_than_toc_mien': { id: 'craft_tu_giai_non_than_toc_mien', name: 'Chế tạo Thần Tốc Miện', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'liet_van_phong_thiet': 10, 'tu_tieu_than_thiet': 5 }, outputs: [{ itemId: 'tu_giai_non_than_toc_mien', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_non_than_toc_mien' },
};
