
import { ItemQuality } from '../../../../types/index.ts';
import { Recipe } from '../../../../types/index.ts';

export const TU_GIAI_GIAP_RECIPES: Record<string, Recipe> = {
    'craft_tu_giai_giap_huyen_vu_giap': { id: 'craft_tu_giai_giap_huyen_vu_giap', name: 'Rèn đúc Huyền Vũ Giáp', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'yeu_lan_huyen_vu_tu_giai': 1, 'tham_hai_o_kim': 10 }, outputs: [{ itemId: 'tu_giai_giap_huyen_vu_giap', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_giap_huyen_vu_giap' },
    'craft_tu_giai_giap_hau_tho_giap': { id: 'craft_tu_giai_giap_hau_tho_giap', name: 'Rèn đúc Hậu Thổ Giáp', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'hau_tho_huyen_tinh': 15, 'yeu_cot_thanh_long_tu_giai': 1 }, outputs: [{ itemId: 'tu_giai_giap_hau_tho_giap', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_giap_hau_tho_giap' },
    'craft_tu_giai_giap_bat_hoai_giap': { id: 'craft_tu_giai_giap_bat_hoai_giap', name: 'Rèn đúc Bất Hoại Giáp', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'thai_at_bach_kim': 10, 'huyen_cuong_thach': 10 }, outputs: [{ itemId: 'tu_giai_giap_bat_hoai_giap', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_giap_bat_hoai_giap' },
    'craft_tu_giai_giap_linh_quang_giap': { id: 'craft_tu_giai_giap_linh_quang_giap', name: 'Rèn đúc Linh Quang Giáp', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'ngan_quang_huyen_thiet': 20, 'yeu_bi_tu_giai': 5 }, outputs: [{ itemId: 'tu_giai_giap_linh_quang_giap', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_giap_linh_quang_giap' },
    'craft_tu_giai_giap_tu_kim_giap': { id: 'craft_tu_giai_giap_tu_kim_giap', name: 'Rèn đúc Tử Kim Giáp', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'tu_kim_khoang': 15, 'thai_at_bach_kim': 5 }, outputs: [{ itemId: 'tu_giai_giap_tu_kim_giap', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_giap_tu_kim_giap' },
    'craft_tu_giai_giap_dieu_quang_giap': { id: 'craft_tu_giai_giap_dieu_quang_giap', name: 'Rèn đúc Diệu Quang Giáp', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'ngan_quang_huyen_thiet': 15, 'hac_dieu_bao_ngoc': 5 }, outputs: [{ itemId: 'tu_giai_giap_dieu_quang_giap', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_giap_dieu_quang_giap' },
    'craft_tu_giai_giap_cong_sinh_giap': { id: 'craft_tu_giai_giap_cong_sinh_giap', name: 'Rèn đúc Cộng Sinh Giáp', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'yeu_bi_cong_sinh_thu_tu_giai': 1, 'yeu_dan_tu_giai': 5 }, outputs: [{ itemId: 'tu_giai_giap_cong_sinh_giap', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_giap_cong_sinh_giap' },
    'craft_tu_giai_giap_thien_bien_giap': { id: 'craft_tu_giai_giap_thien_bien_giap', name: 'Rèn đúc Thiên Biến Giáp', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'ngan_quang_huyen_thiet': 10, 'huyen_quang_ngan_thiet': 10 }, outputs: [{ itemId: 'tu_giai_giap_thien_bien_giap', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_giap_thien_bien_giap' },
    'craft_tu_giai_giap_tich_nhiet_giap': { id: 'craft_tu_giai_giap_tich_nhiet_giap', name: 'Rèn đúc Tịch Nhiệt Giáp', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'lac_duong_huyet_tinh': 10, 'minh_uyen_han_thiet': 10 }, outputs: [{ itemId: 'tu_giai_giap_tich_nhiet_giap', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_giap_tich_nhiet_giap' },
    'craft_tu_giai_giap_thai_an_giap': { id: 'craft_tu_giai_giap_thai_an_giap', name: 'Rèn đúc Thái An Giáp', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'thai_at_bach_kim': 10, 'hau_tho_huyen_tinh': 5 }, outputs: [{ itemId: 'tu_giai_giap_thai_an_giap', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_giap_thai_an_giap' },
};
