
import { ItemQuality } from '../../../../types/index.ts';
import { Recipe } from '../../../../types/index.ts';

export const TU_GIAI_VAN_RECIPES: Record<string, Recipe> = {
    'craft_tu_giai_van_lang_tieu_van': { id: 'craft_tu_giai_van_lang_tieu_van', name: 'Chế tạo Lăng Tiêu Vân', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'tu_tieu_than_thiet': 8, 'yeu_bi_tu_giai': 4 }, outputs: [{ itemId: 'tu_giai_van_lang_tieu_van', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_van_lang_tieu_van' },
    'craft_tu_giai_van_truy_nguyet_van': { id: 'craft_tu_giai_van_truy_nguyet_van', name: 'Chế tạo Truy Nguyệt Vân', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'ngan_quang_huyen_thiet': 10, 'yeu_bi_tu_giai': 5 }, outputs: [{ itemId: 'tu_giai_van_truy_nguyet_van', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_van_truy_nguyet_van' },
    'craft_tu_giai_van_dap_hai_van': { id: 'craft_tu_giai_van_dap_hai_van', name: 'Chế tạo Đạp Hải Vân', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'tham_hai_o_kim': 12, 'yeu_bi_tu_giai': 4 }, outputs: [{ itemId: 'tu_giai_van_dap_hai_van', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_van_dap_hai_van' },
    'craft_tu_giai_van_vo_anh_van': { id: 'craft_tu_giai_van_vo_anh_van', name: 'Chế tạo Vô Ảnh Vân', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'hac_dieu_bao_ngoc': 10, 'yeu_bi_tu_giai': 5 }, outputs: [{ itemId: 'tu_giai_van_vo_anh_van', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_van_vo_anh_van' },
    'craft_tu_giai_van_tat_phong_van': { id: 'craft_tu_giai_van_tat_phong_van', name: 'Chế tạo Tật Phong Vân', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'liet_van_phong_thiet': 15, 'yeu_bi_tu_giai': 5 }, outputs: [{ itemId: 'tu_giai_van_tat_phong_van', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_van_tat_phong_van' },
    'craft_tu_giai_van_ly_phong_van': { id: 'craft_tu_giai_van_ly_phong_van', name: 'Chế tạo Lý Phong Vân', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'liet_van_phong_thiet': 12, 'yeu_bi_tu_giai': 3 }, outputs: [{ itemId: 'tu_giai_van_ly_phong_van', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_van_ly_phong_van' },
    'craft_tu_giai_van_don_tho_van': { id: 'craft_tu_giai_van_don_tho_van', name: 'Chế tạo Độn Thổ Vân', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'hau_tho_huyen_tinh': 12, 'yeu_bi_tu_giai': 3 }, outputs: [{ itemId: 'tu_giai_van_don_tho_van', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_van_don_tho_van' },
    'craft_tu_giai_van_bao_loi_van': { id: 'craft_tu_giai_van_bao_loi_van', name: 'Chế tạo Bạo Lôi Vân', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'tu_tieu_than_thiet': 10, 'yeu_bi_tu_giai': 5 }, outputs: [{ itemId: 'tu_giai_van_bao_loi_van', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_van_bao_loi_van' },
    'craft_tu_giai_van_huyen_quang_van': { id: 'craft_tu_giai_van_huyen_quang_van', name: 'Chế tạo Huyễn Quang Vân', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'ngan_quang_huyen_thiet': 15, 'yeu_bi_tu_giai': 4 }, outputs: [{ itemId: 'tu_giai_van_huyen_quang_van', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_van_huyen_quang_van' },
    'craft_tu_giai_van_dinh_hai_van': { id: 'craft_tu_giai_van_dinh_hai_van', name: 'Chế tạo Định Hải Vân', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'tham_hai_o_kim': 15, 'huyen_cuong_thach': 5 }, outputs: [{ itemId: 'tu_giai_van_dinh_hai_van', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_van_dinh_hai_van' },
};
