
import { ItemQuality } from '../../../../types/index.ts';
import { Recipe } from '../../../../types/index.ts';

export const TU_GIAI_DAO_RECIPES: Record<string, Recipe> = {
    'craft_tu_giai_dao_pha_quan_dao': { id: 'craft_tu_giai_dao_pha_quan_dao', name: 'Rèn đúc Phá Quân Đao', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'huyen_cuong_thach': 15, 'thai_cuong_sa': 10 }, outputs: [{ itemId: 'tu_giai_dao_pha_quan_dao', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_dao_pha_quan_dao' },
    'craft_tu_giai_dao_ho_hon_dao': { id: 'craft_tu_giai_dao_ho_hon_dao', name: 'Rèn đúc Hổ Hồn Đao', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'yeu_cot_thanh_ho_tu_giai': 1, 'hac_dieu_bao_ngoc': 5 }, outputs: [{ itemId: 'tu_giai_dao_ho_hon_dao', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_dao_ho_hon_dao' },
    'craft_tu_giai_dao_tram_kinh_dao': { id: 'craft_tu_giai_dao_tram_kinh_dao', name: 'Rèn đúc Trảm Kình Đao', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'tham_hai_o_kim': 15, 'huyen_cuong_thach': 5 }, outputs: [{ itemId: 'tu_giai_dao_tram_kinh_dao', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_dao_tram_kinh_dao' },
    'craft_tu_giai_dao_hac_dieu_dao': { id: 'craft_tu_giai_dao_hac_dieu_dao', name: 'Rèn đúc Hắc Diệu Đao', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'hac_dieu_bao_ngoc': 15, 'minh_uyen_han_thiet': 5 }, outputs: [{ itemId: 'tu_giai_dao_hac_dieu_dao', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_dao_hac_dieu_dao' },
    'craft_tu_giai_dao_cuong_loi_dao': { id: 'craft_tu_giai_dao_cuong_loi_dao', name: 'Rèn đúc Cuồng Lôi Đao', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'tu_tieu_than_thiet': 12, 'lac_duong_huyet_tinh': 3 }, outputs: [{ itemId: 'tu_giai_dao_cuong_loi_dao', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_dao_cuong_loi_dao' },
    'craft_tu_giai_dao_minh_nguc_dao': { id: 'craft_tu_giai_dao_minh_nguc_dao', name: 'Rèn đúc Minh Ngục Đao', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'minh_uyen_han_thiet': 15, 'yeu_hon_tu_giai': 1 }, outputs: [{ itemId: 'tu_giai_dao_minh_nguc_dao', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_dao_minh_nguc_dao' },
    'craft_tu_giai_dao_lac_nhat_dao': { id: 'craft_tu_giai_dao_lac_nhat_dao', name: 'Rèn đúc Lạc Nhật Đao', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'lac_duong_huyet_tinh': 10, 'xich_diem_tinh_thiet': 10 }, outputs: [{ itemId: 'tu_giai_dao_lac_nhat_dao', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_dao_lac_nhat_dao' },
    'craft_tu_giai_dao_chien_hon_dao': { id: 'craft_tu_giai_dao_chien_hon_dao', name: 'Rèn đúc Chiến Hồn Đao', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'yeu_hon_tu_giai': 2, 'lac_duong_huyet_tinh': 8 }, outputs: [{ itemId: 'tu_giai_dao_chien_hon_dao', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_dao_chien_hon_dao' },
    'craft_tu_giai_dao_ba_nhac_dao': { id: 'craft_tu_giai_dao_ba_nhac_dao', name: 'Rèn đúc Bá Nhạc Đao', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'hau_tho_huyen_tinh': 15, 'huyen_cuong_thach': 10 }, outputs: [{ itemId: 'tu_giai_dao_ba_nhac_dao', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_dao_ba_nhac_dao' },
    'craft_tu_giai_dao_dieu_tinh_dao': { id: 'craft_tu_giai_dao_dieu_tinh_dao', name: 'Rèn đúc Diệu Tinh Đao', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'hac_dieu_bao_ngoc': 15, 'ngan_quang_huyen_thiet': 5 }, outputs: [{ itemId: 'tu_giai_dao_dieu_tinh_dao', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_dao_dieu_tinh_dao' },
};
