
import { ItemQuality } from '../../../../types/index.ts';
import { Recipe } from '../../../../types/index.ts';

export const TU_GIAI_KIEM_RECIPES: Record<string, Recipe> = {
    'craft_tu_giai_kiem_thai_at_kiem': { id: 'craft_tu_giai_kiem_thai_at_kiem', name: 'Rèn đúc Thái Ất Kiếm', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'thai_at_bach_kim': 15, 'ngan_quang_huyen_thiet': 5, 'yeu_dan_tu_giai': 2 }, outputs: [{ itemId: 'tu_giai_kiem_thai_at_kiem', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_kiem_thai_at_kiem' },
    'craft_tu_giai_kiem_tu_tieu_kiem': { id: 'craft_tu_giai_kiem_tu_tieu_kiem', name: 'Rèn đúc Tử Tiêu Kiếm', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'tu_tieu_than_thiet': 12, 'kinh_loi_thach': 10, 'yeu_dan_tu_giai': 3 }, outputs: [{ itemId: 'tu_giai_kiem_tu_tieu_kiem', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_kiem_tu_tieu_kiem' },
    'craft_tu_giai_kiem_minh_uyen_kiem': { id: 'craft_tu_giai_kiem_minh_uyen_kiem', name: 'Rèn đúc Minh Uyên Kiếm', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'minh_uyen_han_thiet': 15, 'tram_ngan_han_thiet': 10 }, outputs: [{ itemId: 'tu_giai_kiem_minh_uyen_kiem', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_kiem_minh_uyen_kiem' },
    'craft_tu_giai_kiem_huyet_duong_kiem': { id: 'craft_tu_giai_kiem_huyet_duong_kiem', name: 'Rèn đúc Huyết Dương Kiếm', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'lac_duong_huyet_tinh': 12, 'ta_duong_muc_kim': 8, 'yeu_dan_tu_giai': 2 }, outputs: [{ itemId: 'tu_giai_kiem_huyet_duong_kiem', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_kiem_huyet_duong_kiem' },
    'craft_tu_giai_kiem_luu_quang_kiem': { id: 'craft_tu_giai_kiem_luu_quang_kiem', name: 'Rèn đúc Lưu Quang Kiếm', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'ngan_quang_huyen_thiet': 20, 'liet_van_phong_thiet': 5 }, outputs: [{ itemId: 'tu_giai_kiem_luu_quang_kiem', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_kiem_luu_quang_kiem' },
    'craft_tu_giai_kiem_nhan_qua_kiem': { id: 'craft_tu_giai_kiem_nhan_qua_kiem', name: 'Rèn đúc Nhân Quả Kiếm', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'thai_at_bach_kim': 10, 'yeu_hon_tu_giai': 1, 'ngu_hanh_linh_ngoc': 5 }, outputs: [{ itemId: 'tu_giai_kiem_nhan_qua_kiem', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_kiem_nhan_qua_kiem' },
    'craft_tu_giai_kiem_vo_hinh_kiem': { id: 'craft_tu_giai_kiem_vo_hinh_kiem', name: 'Rèn đúc Vô Hình Kiếm', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'liet_van_phong_thiet': 15, 'huyen_quang_ngan_thiet': 5 }, outputs: [{ itemId: 'tu_giai_kiem_vo_hinh_kiem', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_kiem_vo_hinh_kiem' },
    'craft_tu_giai_kiem_thach_hoa_kiem': { id: 'craft_tu_giai_kiem_thach_hoa_kiem', name: 'Rèn đúc Thạch Hóa Kiếm', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'hau_tho_huyen_tinh': 15, 'huyen_cuong_thach': 5 }, outputs: [{ itemId: 'tu_giai_kiem_thach_hoa_kiem', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_kiem_thach_hoa_kiem' },
    'craft_tu_giai_kiem_tich_diet_kiem': { id: 'craft_tu_giai_kiem_tich_diet_kiem', name: 'Rèn đúc Tịch Diệt Kiếm', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'minh_uyen_han_thiet': 15, 'hac_dieu_bao_ngoc': 5 }, outputs: [{ itemId: 'tu_giai_kiem_tich_diet_kiem', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_kiem_tich_diet_kiem' },
    'craft_tu_giai_kiem_long_cot_kiem': { id: 'craft_tu_giai_kiem_long_cot_kiem', name: 'Rèn đúc Long Cốt Kiếm', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'yeu_cot_thanh_long_tu_giai': 1, 'thai_at_bach_kim': 5 }, outputs: [{ itemId: 'tu_giai_kiem_long_cot_kiem', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_kiem_long_cot_kiem' },
};
