
import { ItemQuality } from '../../../../types/index.ts';
import { Recipe } from '../../../../types/index.ts';

export const TU_GIAI_CHAM_RECIPES: Record<string, Recipe> = {
    'craft_tu_giai_cham_tang_hon_cham': { id: 'craft_tu_giai_cham_tang_hon_cham', name: 'Chế tạo Táng Hồn Châm', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'minh_uyen_han_thiet': 10, 'yeu_hon_tu_giai': 1 }, outputs: [{ itemId: 'tu_giai_cham_tang_hon_cham', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_cham_tang_hon_cham' },
    'craft_tu_giai_cham_huyet_sat_cham': { id: 'craft_tu_giai_cham_huyet_sat_cham', name: 'Chế tạo Huyết Sát Châm', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'lac_duong_huyet_tinh': 12, 'yeu_cot_tu_giai': 2 }, outputs: [{ itemId: 'tu_giai_cham_huyet_sat_cham', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_cham_huyet_sat_cham' },
    'craft_tu_giai_cham_phe_hon_cham': { id: 'craft_tu_giai_cham_phe_hon_cham', name: 'Chế tạo Phệ Hồn Châm', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'yeu_hon_tu_giai': 3, 'hac_dieu_bao_ngoc': 5 }, outputs: [{ itemId: 'tu_giai_cham_phe_hon_cham', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_cham_phe_hon_cham' },
    'craft_tu_giai_cham_kiep_loi_cham': { id: 'craft_tu_giai_cham_kiep_loi_cham', name: 'Chế tạo Kiếp Lôi Châm', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'tu_tieu_than_thiet': 15, 'yeu_dan_tu_giai': 2 }, outputs: [{ itemId: 'tu_giai_cham_kiep_loi_cham', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_cham_kiep_loi_cham' },
    'craft_tu_giai_cham_do_kiep_cham': { id: 'craft_tu_giai_cham_do_kiep_cham', name: 'Chế tạo Độ Kiếp Châm', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'thai_at_bach_kim': 10, 'yeu_dan_tu_giai': 1 }, outputs: [{ itemId: 'tu_giai_cham_do_kiep_cham', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_cham_do_kiep_cham' },
    'craft_tu_giai_cham_bang_co_cham': { id: 'craft_tu_giai_cham_bang_co_cham', name: 'Chế tạo Băng Cổ Châm', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'minh_uyen_han_thiet': 12, 'yeu_bi_tu_giai': 3 }, outputs: [{ itemId: 'tu_giai_cham_bang_co_cham', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_cham_bang_co_cham' },
    'craft_tu_giai_cham_huyet_lien_cham': { id: 'craft_tu_giai_cham_huyet_lien_cham', name: 'Chế tạo Huyết Liên Châm', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'lac_duong_huyet_tinh': 15 }, outputs: [{ itemId: 'tu_giai_cham_huyet_lien_cham', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_cham_huyet_lien_cham' },
    'craft_tu_giai_cham_phong_linh_cham': { id: 'craft_tu_giai_cham_phong_linh_cham', name: 'Chế tạo Phong Linh Châm', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'liet_van_phong_thiet': 10, 'tu_kim_khoang': 5 }, outputs: [{ itemId: 'tu_giai_cham_phong_linh_cham', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_cham_phong_linh_cham' },
    'craft_tu_giai_cham_pha_tran_cham': { id: 'craft_tu_giai_cham_pha_tran_cham', name: 'Chế tạo Phá Trận Châm', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'tu_tieu_than_thiet': 8, 'huyen_cuong_thach': 4 }, outputs: [{ itemId: 'tu_giai_cham_pha_tran_cham', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_cham_pha_tran_cham' },
    'craft_tu_giai_cham_thien_co_cham': { id: 'craft_tu_giai_cham_thien_co_cham', name: 'Chế tạo Thiên Cơ Châm', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'tinh_van_tinh_thiet': 15, 'yeu_hon_tu_giai': 2 }, outputs: [{ itemId: 'tu_giai_cham_thien_co_cham', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_cham_thien_co_cham' },
};
