
import { ItemQuality } from '../../../../types/index.ts';
import { Recipe } from '../../../../types/index.ts';

export const TU_GIAI_THUONG_RECIPES: Record<string, Recipe> = {
    'craft_tu_giai_thuong_liet_van_thuong': { id: 'craft_tu_giai_thuong_liet_van_thuong', name: 'Rèn đúc Liệt Vân Thương', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'liet_van_phong_thiet': 15, 'ngan_quang_huyen_thiet': 5 }, outputs: [{ itemId: 'tu_giai_thuong_liet_van_thuong', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_thuong_liet_van_thuong' },
    'craft_tu_giai_thuong_thanh_long_thuong': { id: 'craft_tu_giai_thuong_thanh_long_thuong', name: 'Rèn đúc Thánh Long Thương', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'yeu_cot_thanh_long_tu_giai': 1, 'thai_at_bach_kim': 5 }, outputs: [{ itemId: 'tu_giai_thuong_thanh_long_thuong', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_thuong_thanh_long_thuong' },
    'craft_tu_giai_thuong_tran_nhac_thuong': { id: 'craft_tu_giai_thuong_tran_nhac_thuong', name: 'Rèn đúc Trấn Nhạc Thương', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'hau_tho_huyen_tinh': 15, 'huyen_cuong_thach': 10 }, outputs: [{ itemId: 'tu_giai_thuong_tran_nhac_thuong', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_thuong_tran_nhac_thuong' },
    'craft_tu_giai_thuong_than_loi_thuong': { id: 'craft_tu_giai_thuong_than_loi_thuong', name: 'Rèn đúc Thần Lôi Thương', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'tu_tieu_than_thiet': 12, 'yeu_dan_tu_giai': 5 }, outputs: [{ itemId: 'tu_giai_thuong_than_loi_thuong', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_thuong_than_loi_thuong' },
    'craft_tu_giai_thuong_thai_nhat_thuong': { id: 'craft_tu_giai_thuong_thai_nhat_thuong', name: 'Rèn đúc Thái Nhất Thương', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'thai_at_bach_kim': 15, 'huyen_cuong_thach': 5 }, outputs: [{ itemId: 'tu_giai_thuong_thai_nhat_thuong', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_thuong_thai_nhat_thuong' },
    'craft_tu_giai_thuong_vo_cuc_thuong': { id: 'craft_tu_giai_thuong_vo_cuc_thuong', name: 'Rèn đúc Vô Cực Thương', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'ngan_quang_huyen_thiet': 12, 'tinh_van_tinh_thiet': 8 }, outputs: [{ itemId: 'tu_giai_thuong_vo_cuc_thuong', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_thuong_vo_cuc_thuong' },
    'craft_tu_giai_thuong_chan_khong_thuong': { id: 'craft_tu_giai_thuong_chan_khong_thuong', name: 'Rèn đúc Chân Không Thương', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'liet_van_phong_thiet': 10, 'minh_uyen_han_thiet': 5 }, outputs: [{ itemId: 'tu_giai_thuong_chan_khong_thuong', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_thuong_chan_khong_thuong' },
    'craft_tu_giai_thuong_thien_khien_thuong': { id: 'craft_tu_giai_thuong_thien_khien_thuong', name: 'Rèn đúc Thiên Khiển Thương', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'tu_tieu_than_thiet': 15, 'yeu_hon_tu_giai': 1 }, outputs: [{ itemId: 'tu_giai_thuong_thien_khien_thuong', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_thuong_thien_khien_thuong' },
    'craft_tu_giai_thuong_thon_phap_thuong': { id: 'craft_tu_giai_thuong_thon_phap_thuong', name: 'Rèn đúc Thôn Pháp Thương', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'hac_dieu_bao_ngoc': 12, 'yeu_cot_thon_phe_thu_tu_giai': 1 }, outputs: [{ itemId: 'tu_giai_thuong_thon_phap_thuong', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_thuong_thon_phap_thuong' },
    'craft_tu_giai_thuong_ap_hai_thuong': { id: 'craft_tu_giai_thuong_ap_hai_thuong', name: 'Rèn đúc Áp Hải Thương', building: 'blacksmith_forge', requiredTier: ItemQuality.TU_GIAI, requiredProfessionTier: ItemQuality.TU_GIAI, cost: { 'tham_hai_o_kim': 15, 'huyen_cuong_thach': 5 }, outputs: [{ itemId: 'tu_giai_thuong_ap_hai_thuong', chance: 1, amount: 1 }], requiredBlueprint: 'ban_ve_tu_giai_thuong_ap_hai_thuong' },
};
