
import { ItemQuality, EquipmentQuality, ItemType } from '../../../types/index.ts';
import type { Talisman } from '../../../types/index.ts';

export const NHAT_GIAI_PHU: { [key: string]: Talisman } = {
    // Phù Tấn Công
    'hoa_tien_phu': { id: 'hoa_tien_phu', name: 'Hỏa Tiễn Phù', description: 'Bắn ra một mũi tên lửa, tốc độ nhanh hơn Hỏa Cầu Phù nhưng uy lực tương đương.', quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.HA_PHAM, type: ItemType.TALISMAN, effects: { damage: 120 } },
    'bao_liet_hoa_cau_phu': { id: 'bao_liet_hoa_cau_phu', name: 'Bạo Liệt Hỏa Cầu Phù', description: 'Bắn ra một quả cầu lửa, khi va chạm sẽ phát nổ, gây sát thương lửa trên phạm vi nhỏ.', quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, type: ItemType.TALISMAN, effects: { damage: 150 } },
    'thuy_kiem_phu': { id: 'thuy_kiem_phu', name: 'Thuỷ Kiếm Phù', description: 'Triệu hồi một Thanh Kiếm từ trên trời đánh xuống mục tiêu chỉ định. Tốc độ cực nhanh, khó phòng bị.', quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, type: ItemType.TALISMAN, effects: { damage: 250 } },
    'hoa_thuong_phu': { id: 'hoa_thuong_phu', name: 'Hỏa Thương Phù', description: 'Bắn ra một ngọn thương lửa, tốc độ nhanh hơn Hỏa Cầu Phù nhưng uy lực tương đương.', quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.HA_PHAM, type: ItemType.TALISMAN, effects: { damage: 120 } },
    'viem_boc_phu': { id: 'viem_boc_phu', name: 'Viêm Bộc Phù', description: 'Bắn ra một quả cầu lửa, khi va chạm sẽ phát nổ, gây sát thương lửa trên phạm vi nhỏ.', quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, type: ItemType.TALISMAN, effects: { damage: 150 } },
    'thien_loi_phu': { id: 'thien_loi_phu', name: 'Thiên Lôi Phù', description: 'Triệu hồi một tia sét nhỏ từ trên trời đánh xuống mục tiêu chỉ định. Tốc độ cực nhanh, khó phòng bị.', quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, type: ItemType.TALISMAN, effects: { damage: 300 } },
    'dia_ham_phu': { id: 'dia_ham_phu', name: 'Địa Hãm Phù', description: 'Khi ném xuống đất, sẽ nhanh chóng tạo ra một cái hố sâu tạm thời dưới chân mục tiêu, gây bất ngờ và cản trở di chuyển.', quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.HA_PHAM, type: ItemType.TALISMAN, effects: { duration: 2 } },
    'doc_vu_phu': { id: 'doc_vu_phu', name: 'Độc Vụ Phù', description: 'Giải phóng một đám sương độc nhỏ, khi hít phải sẽ gây choáng váng, chóng mặt và suy yếu trong thời gian ngắn.', quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, type: ItemType.TALISMAN, effects: { duration: 3 } },
    'phu_trong_phu': { id: 'phu_trong_phu', name: 'Phụ Trọng Phù', description: 'Bắn ra một đạo phù văn bám vào người mục tiêu, khiến trọng lượng cơ thể của họ tăng lên gấp nhiều lần, làm tốc độ và sự linh hoạt giảm mạnh.', quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, type: ItemType.TALISMAN, effects: { duration: 3 } },
    // Phù Bảo Vệ
    'thuy_mac_thuan_phu': { id: 'thuy_mac_thuan_phu', name: 'Thủy Mạc Thuẫn Phù', description: 'Tạo ra một màn nước mỏng, có hiệu quả tốt trong việc chống lại các đòn tấn công hệ hỏa.', quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.HA_PHAM, type: ItemType.TALISMAN, effects: { shield: 100 } },
    'hau_tho_thuan_phu': { id: 'hau_tho_thuan_phu', name: 'Hậu Thổ Thuẫn Phù', description: 'Tạo ra một tấm khiên bằng đất đá dày và cứng, phòng ngự vật lý vượt trội.', quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, type: ItemType.TALISMAN, effects: { shield: 200 } },
    'kim_quang_tran_phu': { id: 'kim_quang_tran_phu', name: 'Kim Quang Trận Phù', description: 'Tạo ra một kết giới ánh sáng vàng hình bán cầu bao bọc người dùng, có khả năng phòng ngự toàn diện trong thời gian ngắn.', quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, type: ItemType.TALISMAN, effects: { shield: 300, duration: 3 } },
    'thuy_liem_phu': { id: 'thuy_liem_phu', name: 'Thủy Liêm Phù', description: 'Tạo ra một bức rèm bằng nước mỏng, có hiệu quả tốt trong việc chống lại các đòn tấn công hệ hỏa.', quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.HA_PHAM, type: ItemType.TALISMAN, effects: { shield: 100 } },
    'nham_thuan_phu': { id: 'nham_thuan_phu', name: 'Nham Thuẫn Phù', description: 'Tạo ra một tấm khiên bằng nham thạch dày và cứng, phòng ngự vật lý vượt trội.', quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, type: ItemType.TALISMAN, effects: { shield: 200 } },
    'kim_cang_phu': { id: 'kim_cang_phu', name: 'Kim Cang Phù', description: 'Tạo ra một kết giới ánh sáng vàng hình bán cầu bao bọc người dùng, có khả năng phòng ngự toàn diện trong thời gian ngắn.', quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, type: ItemType.TALISMAN, effects: { shield: 300, duration: 3 } },
    'huyen_quang_thuan_phu': { id: 'huyen_quang_thuan_phu', name: 'Huyễn Quang Thuẫn Phù', description: 'Tạo ra một tấm khiên ánh sáng liên tục thay đổi màu sắc và chói lòa. Khả năng phòng ngự vật lý yếu nhưng làm nhiễu loạn thị giác, khiến đối thủ khó nhắm trúng.', quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.HA_PHAM, type: ItemType.TALISMAN, effects: { shield: 80 } },
    'kinh_moc_giap_phu': { id: 'kinh_moc_giap_phu', name: 'Kinh Mộc Giáp Phù', description: 'Bao bọc cơ thể bằng một lớp năng lượng. Khi bị tấn công vật lý, lớp năng lượng này sẽ tự động bắn ra những chiếc gai nhọn gây sát thương ngược lại cho kẻ tấn công.', quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, type: ItemType.TALISMAN, effects: { shield: 150 } },
    'nhu_thuy_thuan_phu': { id: 'nhu_thuy_thuan_phu', name: 'Nhu Thủy Thuẫn Phù', description: 'Tạo ra một tấm khiên bằng nước có mật độ cao. Khiên không vỡ ngay khi va chạm mà sẽ lún vào, hấp thụ và làm tiêu tan phần lớn lực tấn công vật lý.', quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, type: ItemType.TALISMAN, effects: { shield: 250 } },
    // Phù Bỏ Trốn
    'khinh_than_phu': { id: 'khinh_than_phu', name: 'Khinh Thân Phù', description: 'Làm cơ thể nhẹ đi đáng kể, giúp nhảy cao hơn và di chuyển linh hoạt hơn trong thời gian ngắn.', quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.HA_PHAM, type: ItemType.TALISMAN, effects: { duration: 3 } },
    'don_tuc_phu': { id: 'don_tuc_phu', name: 'Độn Tức Phù', description: 'Che giấu hoàn toàn khí tức, tiếng động và hình dáng trong bóng tối hoặc địa hình phức tạp. Hiệu quả cao hơn Ẩn Tức Phù.', quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, type: ItemType.TALISMAN, effects: { duration: 5 } },
    'tat_phong_phu': { id: 'tat_phong_phu', name: 'Tật Phong Phù', description: 'Hóa thành một cơn gió, lao đi với tốc độ cực nhanh trong một quãng đường ngắn (khoảng trăm mét).', quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, type: ItemType.TALISMAN, effects: { duration: 1 } },
    'than_hanh_phu': { id: 'than_hanh_phu', name: 'Thần Hành Phù', description: 'Làm cơ thể nhẹ đi đáng kể, giúp nhảy cao hơn và di chuyển linh hoạt hơn trong thời gian ngắn.', quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.HA_PHAM, type: ItemType.TALISMAN, effects: { duration: 3 } },
    'an_hinh_phu': { id: 'an_hinh_phu', name: 'Ẩn Hình Phù', description: 'Che giấu hoàn toàn khí tức, tiếng động và hình dáng trong bóng tối hoặc địa hình phức tạp. Hiệu quả cao hơn Ẩn Tức Phù.', quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, type: ItemType.TALISMAN, effects: { duration: 5 } },
    'phong_don_phu': { id: 'phong_don_phu', name: 'Phong Độn Phù', description: 'Hóa thành một cơn gió, lao đi với tốc độ cực nhanh trong một quãng đường ngắn (khoảng trăm mét).', quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, type: ItemType.TALISMAN, effects: { duration: 1 } },
    'tinh_am_phu': { id: 'tinh_am_phu', name: 'Tĩnh Âm Phù', description: 'Tạo ra một khu vực nhỏ xung quanh người dùng mà âm thanh bị triệt tiêu, giúp các bước chân trở nên im lặng hơn khi cần hành động bí mật.', quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.HA_PHAM, type: ItemType.TALISMAN, effects: { duration: 5 } },
    'du_dia_phu': { id: 'du_dia_phu', name: 'Du Địa Phù', description: 'Ném ra và biến một vùng đất nhỏ trở nên trơn trượt như bôi dầu, khiến những người đuổi theo dễ bị trượt ngã.', quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.TRUNG_PHAM, type: ItemType.TALISMAN, effects: { duration: 3 } },
    'bich_ho_phu': { id: 'bich_ho_phu', name: 'Bích Hổ Phù', description: 'Cho phép người dùng có khả năng bám dính vào các bề mặt thẳng đứng như tường thành, vách núi trong một khoảng thời gian, giống như con thạch sùng (bích hổ).', quality: ItemQuality.NHAT_GIAI, equipmentQuality: EquipmentQuality.THUONG_PHAM, type: ItemType.TALISMAN, effects: { duration: 10 } },
};
