import { ItemQuality } from '../../../types/index.ts';
import { Recipe } from '../../../types/index.ts';

export const NHAT_GIAI_RECIPES: Record<string, Recipe> = {
    // ==================== VŨ KHÍ ====================
    // --- KIẾM ---
    'craft_xich_dong_co_kiem': { id: 'craft_xich_dong_co_kiem', name: 'Rèn Xích Đồng Cổ Kiếm', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'xich_dong_lk': 10 }, outputs: [{ itemId: 'xich_dong_co_kiem', chance: 1, amount: 1 }] },
    'craft_tinh_thiet_trong_kiem': { id: 'craft_tinh_thiet_trong_kiem', name: 'Rèn Tinh Thiết Trọng Kiếm', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'tinh_thiet': 15 }, outputs: [{ itemId: 'tinh_thiet_trong_kiem', chance: 1, amount: 1 }] },
    'craft_luu_sa_kiem': { id: 'craft_luu_sa_kiem', name: 'Rèn Lưu Sa Kiếm', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'le_kim_sa': 12, 'tinh_thiet': 5 }, outputs: [{ itemId: 'luu_sa_kiem', chance: 1, amount: 1 }] },
    'craft_thanh_ngoc_nhuyen_kiem': { id: 'craft_thanh_ngoc_nhuyen_kiem', name: 'Rèn Thanh Ngọc Nhuyễn Kiếm', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'thanh_ngoc_lk': 8, 'tinh_thiet': 8 }, outputs: [{ itemId: 'thanh_ngoc_nhuyen_kiem', chance: 1, amount: 1 }] },
    'craft_huyen_duong_kiem': { id: 'craft_huyen_duong_kiem', name: 'Rèn Huyễn Dương Kiếm', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'huyen_duong_thach': 10, 'tinh_thiet': 5 }, outputs: [{ itemId: 'huyen_duong_kiem', chance: 1, amount: 1 }] },
    'craft_han_bang_kiem': { id: 'craft_han_bang_kiem', name: 'Rèn Hàn Băng Kiếm', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'han_bang_thach': 15, 'tinh_thiet': 5 }, outputs: [{ itemId: 'han_bang_kiem', chance: 1, amount: 1 }] },
    'craft_tat_phong_kiem': { id: 'craft_tat_phong_kiem', name: 'Rèn Tật Phong Kiếm', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'phong_linh_thach': 15, 'tinh_thiet': 5 }, outputs: [{ itemId: 'tat_phong_kiem', chance: 1, amount: 1 }] },
    'craft_loi_quang_kiem': { id: 'craft_loi_quang_kiem', name: 'Rèn Lôi Quang Kiếm', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'loi_linh_thach': 15, 'tinh_thiet': 5 }, outputs: [{ itemId: 'loi_quang_kiem', chance: 1, amount: 1 }] },
    'craft_thu_cot_kiem': { id: 'craft_thu_cot_kiem', name: 'Rèn Thú Cốt Kiếm', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'yeu_cot_nhat_giai': 20, 'tinh_thiet': 5 }, outputs: [{ itemId: 'thu_cot_kiem', chance: 1, amount: 1 }] },
    'craft_thuy_van_kiem': { id: 'craft_thuy_van_kiem', name: 'Rèn Thủy Vân Kiếm', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'thuy_van_sa': 15, 'tinh_thiet': 5 }, outputs: [{ itemId: 'thuy_van_kiem', chance: 1, amount: 1 }] },
    'craft_thanh_ngoc_kiem': { id: 'craft_thanh_ngoc_kiem', name: 'Rèn Thanh Ngọc Kiếm', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'thanh_ngoc_lk': 20, 'tinh_thiet': 5 }, outputs: [{ itemId: 'thanh_ngoc_kiem', chance: 1, amount: 1 }] },
    'craft_song_sinh_kiem': { id: 'craft_song_sinh_kiem', name: 'Rèn Song Sinh Kiếm', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'hoa_nguyen_thach': 10, 'han_bang_thach': 10, 'tinh_thiet': 5 }, outputs: [{ itemId: 'song_sinh_kiem', chance: 1, amount: 1 }] },

    // --- ĐAO ---
    'craft_xich_dong_phach_dao': { id: 'craft_xich_dong_phach_dao', name: 'Rèn Xích Đồng Phách Đao', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'xich_dong_lk': 12 }, outputs: [{ itemId: 'xich_dong_phach_dao', chance: 1, amount: 1 }] },
    'craft_tinh_thiet_cu_dao': { id: 'craft_tinh_thiet_cu_dao', name: 'Rèn Tinh Thiết Cự Đao', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'tinh_thiet': 20 }, outputs: [{ itemId: 'tinh_thiet_cu_dao', chance: 1, amount: 1 }] },
    'craft_viem_kinh_dao': { id: 'craft_viem_kinh_dao', name: 'Rèn Viêm Kình Đao', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'hoa_nguyen_thach': 12, 'tinh_thiet': 8 }, outputs: [{ itemId: 'viem_kinh_dao', chance: 1, amount: 1 }] },
    'craft_loi_minh_dao': { id: 'craft_loi_minh_dao', name: 'Rèn Lôi Minh Đao', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'loi_linh_thach': 15, 'tinh_thiet': 10 }, outputs: [{ itemId: 'loi_minh_dao', chance: 1, amount: 1 }] },
    'craft_man_cot_dao': { id: 'craft_man_cot_dao', name: 'Rèn Man Cốt Đao', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'yeu_cot_nhat_giai': 25, 'tinh_thiet': 5 }, outputs: [{ itemId: 'man_cot_dao', chance: 1, amount: 1 }] },
    'craft_giao_lan_dao': { id: 'craft_giao_lan_dao', name: 'Rèn Giao Lân Đao', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'yeu_thu_lan_nhat_giai': 30, 'tinh_thiet': 10 }, outputs: [{ itemId: 'giao_lan_dao', chance: 1, amount: 1 }] },
    'craft_toai_bang_dao': { id: 'craft_toai_bang_dao', name: 'Rèn Toái Băng Đao', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'han_bang_thach': 15, 'tinh_thiet': 8 }, outputs: [{ itemId: 'toai_bang_dao', chance: 1, amount: 1 }] },
    'craft_huyen_anh_dao': { id: 'craft_huyen_anh_dao', name: 'Rèn Huyễn Ảnh Đao', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'huyen_duong_thach': 15, 'tinh_thiet': 8 }, outputs: [{ itemId: 'huyen_anh_dao', chance: 1, amount: 1 }] },
    'craft_lang_nha_dao': { id: 'craft_lang_nha_dao', name: 'Rèn Lang Nha Đao', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'yeu_thu_chi_nhat_giai': 20, 'tinh_thiet': 10 }, outputs: [{ itemId: 'lang_nha_dao', chance: 1, amount: 1 }] },
    'craft_kim_sa_doan_hon_dao': { id: 'craft_kim_sa_doan_hon_dao', name: 'Rèn Kim Sa Đoạn Hồn Đao', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'le_kim_sa': 18, 'tinh_thiet': 7 }, outputs: [{ itemId: 'kim_sa_doan_hon_dao', chance: 1, amount: 1 }] },
    'craft_trong_thiet_dao': { id: 'craft_trong_thiet_dao', name: 'Rèn Trọng Thiết Đao', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'tinh_thiet': 22 }, outputs: [{ itemId: 'trong_thiet_dao', chance: 1, amount: 1 }] },
    'craft_le_sa_phach_dao': { id: 'craft_le_sa_phach_dao', name: 'Rèn Lê Sa Phách Đao', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'le_kim_sa': 20, 'tinh_thiet': 10 }, outputs: [{ itemId: 'le_sa_phach_dao', chance: 1, amount: 1 }] },
    'craft_viem_duong_dao': { id: 'craft_viem_duong_dao', name: 'Rèn Viêm Dương Đao', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'hoa_nguyen_thach': 12, 'huyen_duong_thach': 5, 'tinh_thiet': 8 }, outputs: [{ itemId: 'viem_duong_dao', chance: 1, amount: 1 }] },
    'craft_han_phong_dao': { id: 'craft_han_phong_dao', name: 'Rèn Hàn Phong Đao', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'han_bang_thach': 12, 'phong_linh_thach': 8, 'tinh_thiet': 5 }, outputs: [{ itemId: 'han_phong_dao', chance: 1, amount: 1 }] },

    // --- THƯƠNG ---
    'craft_tinh_thiet_truong_thuong': { id: 'craft_tinh_thiet_truong_thuong', name: 'Rèn Tinh Thiết Trường Thương', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'tinh_thiet': 15 }, outputs: [{ itemId: 'tinh_thiet_truong_thuong', chance: 1, amount: 1 }] },
    'craft_liet_hoa_thuong': { id: 'craft_liet_hoa_thuong', name: 'Rèn Liệt Hỏa Thương', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'hoa_nguyen_thach': 10, 'tinh_thiet': 10 }, outputs: [{ itemId: 'liet_hoa_thuong', chance: 1, amount: 1 }] },
    'craft_truy_phong_thuong': { id: 'craft_truy_phong_thuong', name: 'Rèn Truy Phong Thương', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'phong_linh_thach': 12, 'tinh_thiet': 8 }, outputs: [{ itemId: 'truy_phong_thuong', chance: 1, amount: 1 }] },
    'craft_bon_loi_thuong': { id: 'craft_bon_loi_thuong', name: 'Rèn Bôn Lôi Thương', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'loi_linh_thach': 18, 'tinh_thiet': 7 }, outputs: [{ itemId: 'bon_loi_thuong', chance: 1, amount: 1 }] },
    'craft_xa_cot_thuong': { id: 'craft_xa_cot_thuong', name: 'Rèn Xà Cốt Thương', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'yeu_cot_nhat_giai': 22, 'tinh_thiet': 3 }, outputs: [{ itemId: 'xa_cot_thuong', chance: 1, amount: 1 }] },
    'craft_thiet_nha_thuong': { id: 'craft_thiet_nha_thuong', name: 'Rèn Thiết Nha Thương', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'tinh_thiet': 12 }, outputs: [{ itemId: 'thiet_nha_thuong', chance: 1, amount: 1 }] },
    'craft_xuyen_kim_thuong': { id: 'craft_xuyen_kim_thuong', name: 'Rèn Xuyên Kim Thương', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'le_kim_sa': 15, 'tinh_thiet': 10 }, outputs: [{ itemId: 'xuyen_kim_thuong', chance: 1, amount: 1 }] },
    'craft_loi_nha_thuong': { id: 'craft_loi_nha_thuong', name: 'Rèn Lôi Nha Thương', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'loi_linh_thach': 15, 'yeu_thu_chi_nhat_giai': 5, 'tinh_thiet': 5 }, outputs: [{ itemId: 'loi_nha_thuong', chance: 1, amount: 1 }] },
    'craft_ban_thach_thuong': { id: 'craft_ban_thach_thuong', name: 'Rèn Bàn Thạch Thương', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'bach_giao_tho': 15, 'tinh_thiet': 10 }, outputs: [{ itemId: 'ban_thach_thuong', chance: 1, amount: 1 }] },
    'craft_tan_phong_thuong': { id: 'craft_tan_phong_thuong', name: 'Rèn Tàn Phong Thương', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'phong_linh_thach': 20, 'tinh_thiet': 5 }, outputs: [{ itemId: 'tan_phong_thuong', chance: 1, amount: 1 }] },

    // --- CHÂM ---
    'craft_bang_phach_cham': { id: 'craft_bang_phach_cham', name: 'Chế tạo Băng Phách Châm', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'han_bang_thach': 18 }, outputs: [{ itemId: 'bang_phach_cham', chance: 1, amount: 1 }] },
    'craft_hoa_cot_thuy_cham': { id: 'craft_hoa_cot_thuy_cham', name: 'Chế tạo Hóa Cốt Thủy Châm', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'thuy_van_sa': 12, 'yeu_cot_nhat_giai': 8 }, outputs: [{ itemId: 'hoa_cot_thuy_cham', chance: 1, amount: 1 }] },
    'craft_vo_anh_huyen_cham': { id: 'craft_vo_anh_huyen_cham', name: 'Chế tạo Vô Ảnh Huyễn Châm', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'huyen_duong_thach': 20 }, outputs: [{ itemId: 'vo_anh_huyen_cham', chance: 1, amount: 1 }] },
    'craft_tan_loi_cham': { id: 'craft_tan_loi_cham', name: 'Chế tạo Tàn Lôi Châm', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'loi_linh_thach': 15, 'tinh_thiet': 2 }, outputs: [{ itemId: 'tan_loi_cham', chance: 1, amount: 1 }] },
    'craft_hoa_doc_cham': { id: 'craft_hoa_doc_cham', name: 'Chế tạo Hỏa Độc Châm', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'hoa_nguyen_thach': 12, 'yeu_cot_nhat_giai': 5 }, outputs: [{ itemId: 'hoa_doc_cham', chance: 1, amount: 1 }] },
    'craft_pha_khi_cham': { id: 'craft_pha_khi_cham', name: 'Chế tạo Phá Khí Châm', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'tinh_thiet': 15 }, outputs: [{ itemId: 'pha_khi_cham', chance: 1, amount: 1 }] },
    'craft_han_suong_cham': { id: 'craft_han_suong_cham', name: 'Chế tạo Hàn Sương Châm', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'han_bang_thach': 20 }, outputs: [{ itemId: 'han_suong_cham', chance: 1, amount: 1 }] },
    'craft_loi_ma_cham': { id: 'craft_loi_ma_cham', name: 'Chế tạo Lôi Ma Châm', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'loi_linh_thach': 18, 'yeu_cot_nhat_giai': 2 }, outputs: [{ itemId: 'loi_ma_cham', chance: 1, amount: 1 }] },
    'craft_huyen_anh_cham': { id: 'craft_huyen_anh_cham', name: 'Chế tạo Huyễn Ảnh Châm', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'huyen_duong_thach': 15 }, outputs: [{ itemId: 'huyen_anh_cham', chance: 1, amount: 1 }] },
    'craft_truy_hon_cham': { id: 'craft_truy_hon_cham', name: 'Chế tạo Truy Hồn Châm', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'yeu_cot_nhat_giai': 15, 'tinh_thiet': 5 }, outputs: [{ itemId: 'truy_hon_cham', chance: 1, amount: 1 }] },

    // ==================== TRANG BỊ ====================
    // --- GIÁP ---
    'craft_tinh_thiet_trong_giap': { id: 'craft_tinh_thiet_trong_giap', name: 'Rèn Tinh Thiết Trọng Giáp', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'tinh_thiet': 25 }, outputs: [{ itemId: 'tinh_thiet_trong_giap', chance: 1, amount: 1 }] },
    'craft_yeu_bi_nhuyen_giap': { id: 'craft_yeu_bi_nhuyen_giap', name: 'Rèn Yêu Bì Nhuyễn Giáp', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'yeu_bi_nhat_giai': 20, 'tinh_thiet': 5 }, outputs: [{ itemId: 'yeu_bi_nhuyen_giap', chance: 1, amount: 1 }] },
    'craft_thu_lan_giap': { id: 'craft_thu_lan_giap', name: 'Rèn Thú Lân Giáp', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'yeu_thu_lan_nhat_giai': 30, 'tinh_thiet': 10 }, outputs: [{ itemId: 'thu_lan_giap', chance: 1, amount: 1 }] },
    'craft_hoa_nguyen_giap': { id: 'craft_hoa_nguyen_giap', name: 'Rèn Hỏa Nguyên Giáp', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'hoa_nguyen_thach': 20, 'tinh_thiet': 10 }, outputs: [{ itemId: 'hoa_nguyen_giap', chance: 1, amount: 1 }] },
    'craft_giao_tho_giap': { id: 'craft_giao_tho_giap', name: 'Rèn Giao Thổ Giáp', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'bach_giao_tho': 25, 'tinh_thiet': 5 }, outputs: [{ itemId: 'giao_tho_giap', chance: 1, amount: 1 }] },
    'craft_tinh_thiet_phap_bao': { id: 'craft_tinh_thiet_phap_bao', name: 'Rèn Tinh Thiết Pháp Bào', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'tinh_thiet': 20 }, outputs: [{ itemId: 'tinh_thiet_phap_bao', chance: 1, amount: 1 }] },
    'craft_xich_dong_nhuyen_giap': { id: 'craft_xich_dong_nhuyen_giap', name: 'Rèn Xích Đồng Nhuyễn Giáp', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'xich_dong_lk': 20 }, outputs: [{ itemId: 'xich_dong_nhuyen_giap', chance: 1, amount: 1 }] },
    'craft_thanh_ngoc_ho_tam_kinh': { id: 'craft_thanh_ngoc_ho_tam_kinh', name: 'Rèn Thanh Ngọc Hộ Tâm Kính', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'thanh_ngoc_lk': 25 }, outputs: [{ itemId: 'thanh_ngoc_ho_tam_kinh', chance: 1, amount: 1 }] },
    'craft_bach_giao_bi_giap': { id: 'craft_bach_giao_bi_giap', name: 'Rèn Bạch Giao Bì Giáp', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'bach_giao_tho': 15, 'yeu_bi_nhat_giai': 10 }, outputs: [{ itemId: 'bach_giao_bi_giap', chance: 1, amount: 1 }] },
    'craft_nguyen_to_giap': { id: 'craft_nguyen_to_giap', name: 'Rèn Nguyên Tố Giáp', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'hoa_nguyen_thach': 5, 'han_bang_thach': 5, 'loi_linh_thach': 5, 'phong_linh_thach': 5, 'tinh_thiet': 10 }, outputs: [{ itemId: 'nguyen_to_giap', chance: 1, amount: 1 }] },

    // --- VÂN ---
    'craft_phong_hanh_van': { id: 'craft_phong_hanh_van', name: 'Chế tạo Phong Hành Vân', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'phong_linh_thach': 15, 'yeu_bi_nhat_giai': 5 }, outputs: [{ itemId: 'phong_hanh_van', chance: 1, amount: 1 }] },
    'craft_loi_toc_van': { id: 'craft_loi_toc_van', name: 'Chế tạo Lôi Tốc Vân', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'loi_linh_thach': 15, 'yeu_bi_nhat_giai': 5 }, outputs: [{ itemId: 'loi_toc_van', chance: 1, amount: 1 }] },
    'craft_lang_ba_van': { id: 'craft_lang_ba_van', name: 'Chế tạo Lăng Ba Vân', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'thuy_van_sa': 15, 'yeu_bi_nhat_giai': 5 }, outputs: [{ itemId: 'lang_ba_van', chance: 1, amount: 1 }] },
    'craft_tat_phong_bi_van': { id: 'craft_tat_phong_bi_van', name: 'Chế tạo Tật Phong Bì Vân', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'phong_linh_thach': 10, 'yeu_bi_nhat_giai': 10 }, outputs: [{ itemId: 'tat_phong_bi_van', chance: 1, amount: 1 }] },
    'craft_huyen_anh_van': { id: 'craft_huyen_anh_van', name: 'Chế tạo Huyễn Ảnh Vân', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'huyen_duong_thach': 18, 'yeu_bi_nhat_giai': 5 }, outputs: [{ itemId: 'huyen_anh_van', chance: 1, amount: 1 }] },
    'craft_phong_hanh_diep': { id: 'craft_phong_hanh_diep', name: 'Chế tạo Phong Hành Diệp', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'phong_linh_thach': 12 }, outputs: [{ itemId: 'phong_hanh_diep', chance: 1, amount: 1 }] },
    'craft_thuy_van_toa': { id: 'craft_thuy_van_toa', name: 'Chế tạo Thủy Vân Toa', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'thuy_van_sa': 12 }, outputs: [{ itemId: 'thuy_van_toa', chance: 1, amount: 1 }] },
    'craft_loi_quang_bo': { id: 'craft_loi_quang_bo', name: 'Chế tạo Lôi Quang Bộ', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'loi_linh_thach': 15, 'yeu_bi_nhat_giai': 10 }, outputs: [{ itemId: 'loi_quang_bo', chance: 1, amount: 1 }] },
    'craft_huyen_duong_ban': { id: 'craft_huyen_duong_ban', name: 'Chế tạo Huyễn Dương Bàn', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'huyen_duong_thach': 15 }, outputs: [{ itemId: 'huyen_duong_ban', chance: 1, amount: 1 }] },
    'craft_bach_giao_van': { id: 'craft_bach_giao_van', name: 'Chế tạo Bạch Giao Vân', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'bach_giao_tho': 20 }, outputs: [{ itemId: 'bach_giao_van', chance: 1, amount: 1 }] },

    // --- NÓN ---
    'craft_thu_vuong_cot_khoi': { id: 'craft_thu_vuong_cot_khoi', name: 'Chế tạo Thú Vương Cốt Khôi', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'yeu_cot_nhat_giai': 15 }, outputs: [{ itemId: 'thu_vuong_cot_khoi', chance: 1, amount: 1 }] },
    'craft_giao_lan_khoi': { id: 'craft_giao_lan_khoi', name: 'Chế tạo Giao Lân Khôi', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'yeu_thu_lan_nhat_giai': 20 }, outputs: [{ itemId: 'giao_lan_khoi', chance: 1, amount: 1 }] },
    'craft_an_than_ngoc_khoi': { id: 'craft_an_than_ngoc_khoi', name: 'Chế tạo An Thần Ngọc Khôi', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'thanh_ngoc_lk': 15, 'tinh_thiet': 5 }, outputs: [{ itemId: 'an_than_ngoc_khoi', chance: 1, amount: 1 }] },
    'craft_tinh_thiet_ho_tam_kinh_2': { id: 'craft_tinh_thiet_ho_tam_kinh_2', name: 'Rèn Tinh Thiết Hộ Tâm Kính', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'tinh_thiet': 10 }, outputs: [{ itemId: 'tinh_thiet_ho_tam_kinh_2', chance: 1, amount: 1 }] },
    'craft_lang_bi_ho_ngach': { id: 'craft_lang_bi_ho_ngach', name: 'Chế tạo Lang Bì Hộ Ngạch', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHAT_GIAI, cost: { 'yeu_bi_nhat_giai': 10 }, outputs: [{ itemId: 'lang_bi_ho_ngach', chance: 1, amount: 1 }] },

    // --- KHÁC ---
    'craft_library_token_1': { id: 'craft_library_token_1', name: 'Chế tạo Lệnh Bài Tầng 1', building: 'blacksmith_forge', requiredTier: ItemQuality.NHAT_GIAI, requiredProfessionTier: ItemQuality.NHI_GIAI, cost: { 'stone': 50, 'spirit_stone': 200 }, outputs: [{ itemId: 'library_token_1', chance: 1, amount: 1 }] },
};