import { ItemQuality, ProfessionType } from '../../../types/index.ts';
import { Recipe } from '../../../types/index.ts';

export const ALCHEMY_RECIPES: Record<string, Recipe> = {
    // --- Nhất Giai ---
    'craft_tu_khi_dan': {
        id: 'craft_tu_khi_dan',
        name: 'Luyện chế Tụ Khí Đan',
        building: 'alchemist_room',
        requiredTier: ItemQuality.NHAT_GIAI,
        requiredProfessionTier: ItemQuality.NHAT_GIAI,
        cost: { 'nap_khi_thao': 3 },
        outputs: [
            { itemId: 'tu_khi_dan_ha_pham', chance: 0.7, amount: 1 },
            { itemId: 'tu_khi_dan_trung_pham', chance: 0.25, amount: 1 },
            { itemId: 'tu_khi_dan_thuong_pham', chance: 0.05, amount: 1 }
        ],
    },
    'craft_hoi_khi_dan': {
        id: 'craft_hoi_khi_dan',
        name: 'Luyện chế Hồi Khí Đan',
        building: 'alchemist_room',
        requiredTier: ItemQuality.NHAT_GIAI,
        requiredProfessionTier: ItemQuality.NHAT_GIAI,
        cost: { 'man_da_can': 2, 'nap_khi_thao': 1 },
        outputs: [
            { itemId: 'hoi_khi_dan_ha_pham', chance: 0.8, amount: 1 },
            { itemId: 'hoi_khi_dan_trung_pham', chance: 0.3, amount: 1 },
            { itemId: 'hoi_khi_dan_thuong_pham', chance: 0.08, amount: 1 }
        ],
    },
    'craft_bao_khi_dan': {
        id: 'craft_bao_khi_dan',
        name: 'Luyện chế Bạo Khí Đan',
        building: 'alchemist_room',
        requiredTier: ItemQuality.NHAT_GIAI,
        requiredProfessionTier: ItemQuality.NHAT_GIAI,
        cost: { tu_linh_thao: 3, ngung_khi_qua: 1, thanh_linh_thao: 1 },
        outputs: [
            { itemId: 'bao_khi_dan_ha_pham', chance: 0.6, amount: 1 },
            { itemId: 'bao_khi_dan_trung_pham', chance: 0.2, amount: 1 },
            { itemId: 'bao_khi_dan_thuong_pham', chance: 0.03, amount: 1 }
        ],
    },
    'craft_an_mach_hoan': {
        id: 'craft_an_mach_hoan',
        name: 'Luyện chế An Mạch Hoàn',
        building: 'alchemist_room',
        requiredTier: ItemQuality.NHAT_GIAI,
        requiredProfessionTier: ItemQuality.NHAT_GIAI,
        cost: { tinh_linh_qua: 2, thanh_linh_thao: 2, thanh_ngoc_truc: 1 },
        outputs: [
            { itemId: 'an_mach_hoan_ha_pham', chance: 0.6, amount: 1 },
            { itemId: 'an_mach_hoan_trung_pham', chance: 0.25, amount: 1 },
            { itemId: 'an_mach_hoan_thuong_pham', chance: 0.05, amount: 1 }
        ],
    },
    'craft_hoi_xuan_sinh_co_cao': {
        id: 'craft_hoi_xuan_sinh_co_cao',
        name: 'Luyện chế Hồi Xuân Sinh Cơ Cao',
        building: 'alchemist_room',
        requiredTier: ItemQuality.NHAT_GIAI,
        requiredProfessionTier: ItemQuality.NHAT_GIAI,
        cost: { hoi_xuan_thao: 4, thanh_ngoc_qua: 1, thiet_diep_moc: 1 },
        outputs: [
            { itemId: 'hoi_xuan_sinh_co_cao_ha_pham', chance: 0.7, amount: 1 },
            { itemId: 'hoi_xuan_sinh_co_cao_trung_pham', chance: 0.3, amount: 1 },
            { itemId: 'hoi_xuan_sinh_co_cao_thuong_pham', chance: 0.1, amount: 1 }
        ],
    },
    'craft_xich_hoa_tan': {
        id: 'craft_xich_hoa_tan',
        name: 'Luyện chế Xích Hỏa Tán',
        building: 'alchemist_room',
        requiredTier: ItemQuality.NHAT_GIAI,
        requiredProfessionTier: ItemQuality.NHAT_GIAI,
        cost: { hoa_linh_thao: 2, ngung_khi_qua: 1, tinh_linh_qua: 1 },
        outputs: [
            { itemId: 'xich_hoa_tan_ha_pham', chance: 0.65, amount: 1 },
            { itemId: 'xich_hoa_tan_trung_pham', chance: 0.2, amount: 1 },
            { itemId: 'xich_hoa_tan_thuong_pham', chance: 0.04, amount: 1 }
        ],
    },
    'craft_u_tuc_hoan': {
        id: 'craft_u_tuc_hoan',
        name: 'Luyện chế U Tức Hoàn',
        building: 'alchemist_room',
        requiredTier: ItemQuality.NHAT_GIAI,
        requiredProfessionTier: ItemQuality.NHAT_GIAI,
        cost: { hac_linh_co: 3, thanh_linh_thao: 1, tu_linh_thao: 1 },
        outputs: [
            { itemId: 'u_tuc_hoan_ha_pham', chance: 0.8, amount: 1 },
            { itemId: 'u_tuc_hoan_trung_pham', chance: 0.3, amount: 1 },
            { itemId: 'u_tuc_hoan_thuong_pham', chance: 0.1, amount: 1 }
        ],
    },

    // --- Nhị Giai ---
    'craft_truc_co_dan': {
        id: 'craft_truc_co_dan',
        name: 'Luyện chế Trúc Cơ Đan',
        building: 'alchemist_room',
        requiredTier: ItemQuality.NHI_GIAI,
        requiredProfessionTier: ItemQuality.NHI_GIAI,
        cost: { 'hoang_linh_chi': 1, 'duong_cuc_qua': 1, 'tu_khi_hoa': 3, 'tu_ngoc_truc': 1 },
        outputs: [
            { itemId: 'truc_co_dan_ha_pham', chance: 0.6, amount: 1 },
            { itemId: 'truc_co_dan_trung_pham', chance: 0.25, amount: 1 },
            { itemId: 'truc_co_dan_thuong_pham', chance: 0.05, amount: 1 },
        ],
        requiredBlueprint: 'dan_phuong_truc_co_dan',
    },
    'craft_chan_nguyen_dan': {
        id: 'craft_chan_nguyen_dan',
        name: 'Luyện chế Chân Nguyên Đan',
        building: 'alchemist_room',
        requiredTier: ItemQuality.NHI_GIAI,
        requiredProfessionTier: ItemQuality.NHI_GIAI,
        cost: { 'chan_nguyen_qua': 1, 'hoang_linh_chi': 1, 'tu_khi_hoa': 2 },
        outputs: [
            { itemId: 'chan_nguyen_dan_ha_pham', chance: 0.5, amount: 1 },
            { itemId: 'chan_nguyen_dan_trung_pham', chance: 0.2, amount: 1 },
            { itemId: 'chan_nguyen_dan_thuong_pham', chance: 0.08, amount: 1 }
        ],
        requiredBlueprint: 'dan_phuong_chan_nguyen_dan',
    },
    'craft_bich_huyet_duong_thuong_hoan': {
        id: 'craft_bich_huyet_duong_thuong_hoan',
        name: 'Luyện chế Bích Huyết Dưỡng Thương Hoàn',
        building: 'alchemist_room',
        requiredTier: ItemQuality.NHI_GIAI,
        requiredProfessionTier: ItemQuality.NHI_GIAI,
        cost: { 'bich_huyet_thao': 5, 'hong_huyet_sam': 1, 'hoang_linh_chi': 1 },
        outputs: [
            { itemId: 'bich_huyet_duong_thuong_hoan_ha_pham', chance: 0.55, amount: 1 },
            { itemId: 'bich_huyet_duong_thuong_hoan_trung_pham', chance: 0.22, amount: 1 },
            { itemId: 'bich_huyet_duong_thuong_hoan_thuong_pham', chance: 0.07, amount: 1 }
        ],
        requiredBlueprint: 'dan_phuong_bich_huyet_duong_thuong_hoan',
    },
    'craft_doan_cot_hoan': {
        id: 'craft_doan_cot_hoan',
        name: 'Luyện chế Đoán Cốt Hoàn',
        building: 'alchemist_room',
        requiredTier: ItemQuality.NHI_GIAI,
        requiredProfessionTier: ItemQuality.NHI_GIAI,
        cost: { 'ma_nao_chi': 1, 'kim_duong_moc': 1, 'hoang_linh_chi': 1 },
        outputs: [
            { itemId: 'doan_cot_hoan_ha_pham', chance: 0.5, amount: 1 },
            { itemId: 'doan_cot_hoan_trung_pham', chance: 0.2, amount: 1 },
            { itemId: 'doan_cot_hoan_thuong_pham', chance: 0.06, amount: 1 }
        ],
        requiredBlueprint: 'dan_phuong_doan_cot_hoan',
    },
    'craft_duong_viem_dan': {
        id: 'craft_duong_viem_dan',
        name: 'Luyện chế Dương Viêm Đan',
        building: 'alchemist_room',
        requiredTier: ItemQuality.NHI_GIAI,
        requiredProfessionTier: ItemQuality.NHI_GIAI,
        cost: { 'duong_cuc_qua': 1, 'viem_hoa_co': 1, 'hoa_van_truc': 1 },
        outputs: [
            { itemId: 'duong_viem_dan', chance: 0.4, amount: 1 },
        ],
        requiredBlueprint: 'dan_phuong_duong_viem_dan',
    },
    'craft_han_ngung_tan': {
        id: 'craft_han_ngung_tan',
        name: 'Luyện chế Hàn Ngưng Tán',
        building: 'alchemist_room',
        requiredTier: ItemQuality.NHI_GIAI,
        requiredProfessionTier: ItemQuality.NHI_GIAI,
        cost: { 'bang_linh_qua': 1, 'am_ngung_co': 1, 'tu_ngoc_truc': 1 },
        outputs: [
            { itemId: 'han_ngung_tan', chance: 0.4, amount: 1 },
        ],
        requiredBlueprint: 'dan_phuong_han_ngung_tan',
    },

    // --- Tam Giai ---
    'craft_tuyet_lien_duong_hon_dan': {
        id: 'craft_tuyet_lien_duong_hon_dan',
        name: 'Luyện chế Tuyết Liên Dưỡng Hồn Đan',
        building: 'alchemist_room',
        requiredTier: ItemQuality.TAM_GIAI,
        requiredProfessionTier: ItemQuality.TAM_GIAI,
        cost: { tuyet_linh_chi: 1, u_hon_thao: 1, bach_ngoc_san_ho_moc: 1 },
        outputs: [
            { itemId: 'tuyet_lien_duong_hon_dan_ha_pham', chance: 0.5, amount: 1 },
            { itemId: 'tuyet_lien_duong_hon_dan_trung_pham', chance: 0.2, amount: 1 },
            { itemId: 'tuyet_lien_duong_hon_dan_thuong_pham', chance: 0.05, amount: 1 },
        ],
        requiredBlueprint: 'dan_phuong_tuyet_lien_duong_hon_dan',
    },
    'craft_sinh_co_tai_tao_dan': {
        id: 'craft_sinh_co_tai_tao_dan',
        name: 'Luyện chế Sinh Cơ Tái Tạo Đan',
        building: 'alchemist_room',
        requiredTier: ItemQuality.TAM_GIAI,
        requiredProfessionTier: ItemQuality.TAM_GIAI,
        cost: { sinh_nguyen_co: 1, ngoc_nguyen_hoi_xuan_hoa: 1, huyet_ngoc_sam: 1 },
        outputs: [
            { itemId: 'sinh_co_tai_tao_dan_ha_pham', chance: 0.4, amount: 1 },
            { itemId: 'sinh_co_tai_tao_dan_trung_pham', chance: 0.15, amount: 1 },
            { itemId: 'sinh_co_tai_tao_dan_thuong_pham', chance: 0.03, amount: 1 },
        ],
        requiredBlueprint: 'dan_phuong_sinh_co_tai_tao_dan',
    },
    'craft_nghe_thuong_mong_ao_dan': {
        id: 'craft_nghe_thuong_mong_ao_dan',
        name: 'Luyện chế Nghê Thường Mộng Ảo Đan',
        building: 'alchemist_room',
        requiredTier: ItemQuality.TAM_GIAI,
        requiredProfessionTier: ItemQuality.TAM_GIAI,
        cost: { nghe_thuong_thao: 1, u_hon_thao: 1, that_tinh_thao: 1 },
        outputs: [
            { itemId: 'nghe_thuong_mong_ao_dan_ha_pham', chance: 0.6, amount: 1 },
            { itemId: 'nghe_thuong_mong_ao_dan_trung_pham', chance: 0.2, amount: 1 },
            { itemId: 'nghe_thuong_mong_ao_dan_thuong_pham', chance: 0.05, amount: 1 },
        ],
        requiredBlueprint: 'dan_phuong_nghe_thuong_mong_ao_dan',
    },
    'craft_huyet_sat_ma_the_dan': {
        id: 'craft_huyet_sat_ma_the_dan',
        name: 'Luyện chế Huyết Sát Ma Thể Đan',
        building: 'alchemist_room',
        requiredTier: ItemQuality.TAM_GIAI,
        requiredProfessionTier: ItemQuality.TAM_GIAI,
        cost: { huyet_ngoc_sam: 1, diem_duong_moc: 1 },
        outputs: [{ itemId: 'huyet_sat_ma_the_dan', chance: 0.3, amount: 1 }],
        requiredBlueprint: 'dan_phuong_huyet_sat_ma_the_dan',
    },
    'craft_chuyen_kim_dan': {
        id: 'craft_chuyen_kim_dan',
        name: 'Luyện chế Chuyển Kim Đan',
        building: 'alchemist_room',
        requiredTier: ItemQuality.TAM_GIAI,
        requiredProfessionTier: ItemQuality.TAM_GIAI,
        cost: { tu_van_sam: 1, sinh_nguyen_co: 1, that_tinh_thao: 3, ngoc_nguyen_hoi_xuan_hoa: 1 },
        outputs: [{ itemId: 'chuyen_kim_dan', chance: 0.2, amount: 1 }],
        requiredBlueprint: 'dan_phuong_chuyen_kim_dan',
    },
    'craft_huyet_sat_kim_dan': {
        id: 'craft_huyet_sat_kim_dan',
        name: 'Luyện chế Huyết Sát Kim Đan',
        building: 'alchemist_room',
        requiredTier: ItemQuality.TAM_GIAI,
        requiredProfessionTier: ItemQuality.TAM_GIAI,
        cost: { tinh_huyet_truc_co: 10, sinh_nguyen_co: 1, that_tinh_thao: 3, ngoc_nguyen_hoi_xuan_hoa: 1 },
        outputs: [{ itemId: 'huyet_sat_kim_dan', chance: 0.1, amount: 1 }],
        requiredBlueprint: 'dan_phuong_huyet_sat_kim_dan',
    },
     'craft_huyet_sam_bao_khi_dan': {
        id: 'craft_huyet_sam_bao_khi_dan',
        name: 'Luyện chế Huyết Sâm Bạo Khí Đan',
        building: 'alchemist_room',
        requiredTier: ItemQuality.TAM_GIAI,
        requiredProfessionTier: ItemQuality.TAM_GIAI,
        cost: { huyet_ngoc_sam: 1, tu_van_sam: 1, bich_huyet_thao: 5 },
        outputs: [{ itemId: 'huyet_sam_bao_khi_dan', chance: 0.2, amount: 1 }],
        requiredBlueprint: 'dan_phuong_huyet_sam_bao_khi_dan',
    },
    'craft_dien_tho_hoan': {
        id: 'craft_dien_tho_hoan',
        name: 'Luyện chế Diên Thọ Hoàn',
        building: 'alchemist_room',
        requiredTier: ItemQuality.TAM_GIAI,
        requiredProfessionTier: ItemQuality.TAM_GIAI,
        cost: { sinh_nguyen_co: 1, ngoc_nguyen_hoi_xuan_hoa: 1, bach_ngoc_san_ho_moc: 1 },
        outputs: [{ itemId: 'dien_tho_hoan', chance: 0.15, amount: 1 }],
        requiredBlueprint: 'dan_phuong_dien_tho_hoan',
    },

    // --- Tứ Giai ---
    'craft_thien_nguyen_tay_anh_dan': {
        id: 'craft_thien_nguyen_tay_anh_dan',
        name: 'Luyện chế Thiên Nguyên Tẩy Anh Đan',
        building: 'alchemist_room',
        requiredTier: ItemQuality.TU_GIAI,
        requiredProfessionTier: ItemQuality.TU_GIAI,
        cost: { 'thien_nguyen_qua': 1, 'kim_chi_luc_diep_hoa': 1, 'nam_hai_tu_diem_truc': 1 },
        outputs: [{ itemId: 'thien_nguyen_tay_anh_dan', chance: 0.1, amount: 1 }],
        requiredBlueprint: 'dan_phuong_thien_nguyen_tay_anh_dan',
    },
    'craft_phuong_van_tai_tao_tan': {
        id: 'craft_phuong_van_tai_tao_tan',
        name: 'Luyện chế Phượng Văn Tái Tạo Tán',
        building: 'alchemist_room',
        requiredTier: ItemQuality.TU_GIAI,
        requiredProfessionTier: ItemQuality.TU_GIAI,
        cost: { 'phuong_van_linh_chi': 1, 'thien_linh_chi': 1, 'tran_nguc_qua': 1 },
        outputs: [{ itemId: 'phuong_van_tai_tao_tan', chance: 0.1, amount: 1 }],
        requiredBlueprint: 'dan_phuong_phuong_van_tai_tao_tan',
    },
    'craft_tu_long_hoa_the_hoan': {
        id: 'craft_tu_long_hoa_the_hoan',
        name: 'Luyện chế Tử Long Hóa Thể Hoàn',
        building: 'alchemist_room',
        requiredTier: ItemQuality.TU_GIAI,
        requiredProfessionTier: ItemQuality.TU_GIAI,
        cost: { 'tu_long_qua': 1, 'long_can_thao': 1, 'huyet_long_moc': 1 },
        outputs: [{ itemId: 'tu_long_hoa_the_hoan', chance: 0.1, amount: 1 }],
        requiredBlueprint: 'dan_phuong_tu_long_hoa_the_hoan',
    },
    'craft_tran_nguc_thanh_tam_dan': {
        id: 'craft_tran_nguc_thanh_tam_dan',
        name: 'Luyện chế Trấn Ngục Thanh Tâm Đan',
        building: 'alchemist_room',
        requiredTier: ItemQuality.TU_GIAI,
        requiredProfessionTier: ItemQuality.TU_GIAI,
        cost: { 'tran_nguc_qua': 1, 'thien_nguyen_qua': 1, 'nam_hai_tu_diem_truc': 1 },
        outputs: [{ itemId: 'tran_nguc_thanh_tam_dan', chance: 0.1, amount: 1 }],
        requiredBlueprint: 'dan_phuong_tran_nguc_thanh_tam_dan',
    },
    'craft_hoa_anh_dan': {
        id: 'craft_hoa_anh_dan',
        name: 'Luyện chế Hoá Anh Đan',
        building: 'alchemist_room',
        requiredTier: ItemQuality.TU_GIAI,
        requiredProfessionTier: ItemQuality.TU_GIAI,
        cost: { 'hoa_anh_qua': 1, 'tran_nguc_qua': 1, 'phuong_van_linh_chi': 1, 'long_can_thao': 1 },
        outputs: [{ itemId: 'hoa_anh_dan', chance: 0.05, amount: 1 }],
        requiredBlueprint: 'dan_phuong_hoa_anh_dan',
    },
    'craft_du_long_huong': {
        id: 'craft_du_long_huong',
        name: 'Chế tác Dụ Long Hương',
        building: 'alchemist_room',
        requiredTier: ItemQuality.TU_GIAI,
        requiredProfessionTier: ItemQuality.TU_GIAI,
        cost: { 'du_long_thao': 1, 'tu_long_qua': 1, 'huyet_long_moc': 1 },
        outputs: [{ itemId: 'du_long_huong', chance: 0.5, amount: 1 }],
    },
    'craft_cuu_chuyen_long_hon_dan': {
        id: 'craft_cuu_chuyen_long_hon_dan',
        name: 'Luyện chế Cửu Chuyển Long Hồn Đan',
        building: 'alchemist_room',
        requiredTier: ItemQuality.TU_GIAI,
        requiredProfessionTier: ItemQuality.TU_GIAI,
        cost: { 'tu_long_qua': 1, 'phuong_van_linh_chi': 1, 'long_can_thao': 1 },
        outputs: [{ itemId: 'cuu_chuyen_long_hon_dan', chance: 0.1, amount: 1 }],
        requiredBlueprint: 'dan_phuong_cuu_chuyen_long_hon_dan',
    },
    'craft_dien_tho_dan': {
        id: 'craft_dien_tho_dan',
        name: 'Luyện chế Diên Thọ Đan',
        building: 'alchemist_room',
        requiredTier: ItemQuality.TU_GIAI,
        requiredProfessionTier: ItemQuality.TU_GIAI,
        cost: { 'thien_linh_chi': 1, 'phuong_van_linh_chi': 1, 'thien_nguyen_qua': 1 },
        outputs: [{ itemId: 'dien_tho_dan', chance: 0.05, amount: 1 }],
        requiredBlueprint: 'dan_phuong_dien_tho_dan',
    },
    
    // --- Ngũ Giai ---
    'craft_hoa_vi_canh_dan': {
        id: 'craft_hoa_vi_canh_dan',
        name: 'Luyện chế Hoá Vi Cảnh Đan',
        building: 'alchemist_room',
        requiredTier: ItemQuality.NGU_GIAI,
        requiredProfessionTier: ItemQuality.NGU_GIAI,
        cost: { 'tu_van_long_tien_sam': 1, 'thien_nguyen_dao_qua': 1 },
        outputs: [{ itemId: 'hoa_vi_canh_dan', chance: 0.05, amount: 1 }],
        requiredBlueprint: 'dan_phuong_hoa_vi_canh_dan',
    },
    'craft_tien_khi_quy_nguyen_dan': {
        id: 'craft_tien_khi_quy_nguyen_dan',
        name: 'Luyện chế Tiên Khí Quy Nguyên Đan',
        building: 'alchemist_room',
        requiredTier: ItemQuality.NGU_GIAI,
        requiredProfessionTier: ItemQuality.NGU_GIAI,
        cost: { 'tu_van_long_tien_sam': 1, 'cuu_diep_kim_lien': 1 },
        outputs: [{ itemId: 'tien_khi_quy_nguyen_dan', chance: 0.05, amount: 1 }],
        requiredBlueprint: 'dan_phuong_tien_khi_quy_nguyen_dan',
    },
    'craft_phuong_tuy_sinh_huyet_dan': {
        id: 'craft_phuong_tuy_sinh_huyet_dan',
        name: 'Luyện chế Phượng Tủy Sinh Huyết Đan',
        building: 'alchemist_room',
        requiredTier: ItemQuality.NGU_GIAI,
        requiredProfessionTier: ItemQuality.NGU_GIAI,
        cost: { 'phuong_huyet_qua': 1, 'truong_sinh_qua': 1 },
        outputs: [{ itemId: 'phuong_tuy_sinh_huyet_dan', chance: 0.05, amount: 1 }],
        requiredBlueprint: 'dan_phuong_phuong_tuy_sinh_huyet_dan',
    },
    'craft_truong_sinh_dao_qua_dan': {
        id: 'craft_truong_sinh_dao_qua_dan',
        name: 'Luyện chế Trường Sinh Đạo Quả Đan',
        building: 'alchemist_room',
        requiredTier: ItemQuality.NGU_GIAI,
        requiredProfessionTier: ItemQuality.NGU_GIAI,
        cost: { 'truong_sinh_qua': 1, 'thien_nguyen_dao_qua': 1 },
        outputs: [{ itemId: 'truong_sinh_dao_qua_dan', chance: 0.02, amount: 1 }],
        requiredBlueprint: 'dan_phuong_truong_sinh_dao_qua_dan',
    },
    'craft_huyet_duong_phan_thien_dan': {
        id: 'craft_huyet_duong_phan_thien_dan',
        name: 'Luyện chế Huyết Dương Phần Thiên Đan',
        building: 'alchemist_room',
        requiredTier: ItemQuality.NGU_GIAI,
        requiredProfessionTier: ItemQuality.NGU_GIAI,
        cost: { 'huyet_hoa_phu_tang': 1, 'phuong_huyet_qua': 1, 'phuc_long_dang': 1 },
        outputs: [{ itemId: 'huyet_duong_phan_thien_dan', chance: 0.1, amount: 1 }],
        requiredBlueprint: 'dan_phuong_huyet_duong_phan_thien_dan',
    },
};